<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>SobekCM_Engine</AssemblyName>
    <RootNamespace>SobekCM_Engine</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SobekCM_Core\SobekCM_Core.csproj" />
    <ProjectReference Include="..\SobekCM_Engine_Library\SobekCM_Engine_Library.csproj" />
    <ProjectReference Include="..\SobekCM_Resource_Object\SobekCM_Resource_Object.csproj" />
    <ProjectReference Include="..\SobekCM_Tools\SobekCM_Tools.csproj" />
  </ItemGroup>

</Project>
