#region Using directives

using SobekCM.Core.Builder;
using System;
using System.IO;

#endregion

namespace SobekCM.Builder_Library.Modules.Items
{
    /// <summary> Item-level submission package module deletes the non-master TIFFs generated by
    /// <see cref="ConvertJpeg2000sItemModule"/> from a JPEG2000, once they are no longer needed
    /// (e.g. after OCR has run against them) </summary>
    /// <remarks> This class implements the <see cref="abstractSubmissionPackageModule" /> abstract class and implements the <see cref="iSubmissionPackageModule" /> interface. </remarks>
    public class DeleteNonMasterTiffsModule : abstractSubmissionPackageModule
    {
        /// <summary> Deletes the non-master TIFFs generated by <see cref="ConvertJpeg2000sItemModule"/>,
        /// as listed in the processing file it leaves behind </summary>
        /// <param name="Resource"> Incoming digital resource object </param>
        /// <returns> TRUE if processing can continue, FALSE if a critical error occurred which should stop all processing </returns>
        public override bool DoWork(Incoming_Digital_Resource Resource)
        {
            // Explicitly asked to keep these TIFFs around, so nothing to do
            if (Resource.ProcessingFlags.Contains(ProcessingFlag_Constants.RetainNonMasterTiffs))
                return true;

            // Nothing was flagged as generated, so nothing to clean up
            if (!Resource.ProcessingFlags.Contains(ProcessingFlag_Constants.NonMasterTiffs))
                return true;

            string resourceFolder = Resource.Resource_Folder;
            string procFile = Path.Combine(resourceFolder, "generated_tiffs.proc");

            if (!File.Exists(procFile))
                return true;

            try
            {
                string[] lines = File.ReadAllLines(procFile);
                foreach (string thisLine in lines)
                {
                    if (String.IsNullOrWhiteSpace(thisLine))
                        continue;

                    string tiff_file = Path.Combine(resourceFolder, thisLine.Trim());
                    if (File.Exists(tiff_file))
                        File.Delete(tiff_file);
                }

                File.Delete(procFile);
            }
            catch (Exception ee)
            {
                OnError("Error deleting non-master TIFFs in DeleteNonMasterTiffsModule\n" + ee.Message, Resource.BibID + ":" + Resource.VID, Resource.METS_Type_String, Resource.BuilderLogId);
                return false;
            }

            return true;
        }
    }
}
