SET NOCOUNT ON;

/*
	SobekCM Version 5.0.0 schema verification script

	Compares this database's actual table/column definitions (type, length,
	nullability) against the expected schema captured in ver5_tables.sql.
	Run after each upgrade to confirm every table's columns match exactly.

	Only PRINTs when something doesn't match - a clean run produces just the
	final "Schema comparison complete." line (plus whatever row counts SSMS
	reports for the temp table population, if "Messages" includes those).

	Does not check indexes, foreign keys, constraints, or the presence of
	tables/columns not listed here (this only knows about the ~106 tables
	present in ver5_tables.sql at the time this script was generated).
*/

IF OBJECT_ID('tempdb..#ExpectedSchema') IS NOT NULL DROP TABLE #ExpectedSchema;

CREATE TABLE #ExpectedSchema (
	TableName   sysname     NOT NULL,
	ColumnName  sysname     NOT NULL,
	DataType    varchar(50) NOT NULL,
	MaxLen      int         NULL,   -- character length; -1 = max; NULL = not length-bound (int, bit, datetime, float, etc.)
	IsNullable  bit         NOT NULL
);

INSERT INTO #ExpectedSchema (TableName, ColumnName, DataType, MaxLen, IsNullable) VALUES
('Archive_Item_Archived_File','ArchivedFileID','int',NULL,0),
('Archive_Item_Archived_File','ItemID','int',NULL,0),
('Archive_Item_Archived_File','FileName','varchar',255,0),
('Archive_Item_Archived_File','FileExtension','varchar',20,0),
('Archive_Item_Archived_File_Copy','ArchivedFileCopyID','int',NULL,0),
('Archive_Item_Archived_File_Copy','SnapshotID','int',NULL,0),
('Archive_Item_Archived_File_Copy','ArchiveLocationID','smallint',NULL,0),
('Archive_Item_Archived_File_Copy','StoragePath','varchar',1000,0),
('Archive_Item_Archived_File_Copy','StoredDate','datetime',NULL,0),
('Archive_Item_Archived_File_Copy','VerifiedDate','datetime',NULL,1),
('Archive_Item_Archived_File_Copy','Status','varchar',20,0),
('Archive_Item_Archived_File_Snapshot','SnapshotID','int',NULL,0),
('Archive_Item_Archived_File_Snapshot','ArchivedFileID','int',NULL,0),
('Archive_Item_Archived_File_Snapshot','FileSize','bigint',NULL,0),
('Archive_Item_Archived_File_Snapshot','OriginalCreationDate','datetime',NULL,0),
('Archive_Item_Archived_File_Snapshot','SHA256_Hash','char',64,0),
('Archive_Item_Archived_File_Snapshot','SnapshotDate','datetime',NULL,0),
('Archive_Item_Archived_File_Snapshot','MimeType','varchar',100,1),
('Archive_Item_Archived_File_Snapshot','EncodingDetails','varchar',500,1),
('Archive_Location','ArchiveLocationID','smallint',NULL,0),
('Archive_Location','LocationName','varchar',50,0),
('Archive_Location','LocationType','varchar',20,0),
('Archive_Location','ContainerName','varchar',255,1),
('Archive_Location','IsActive','bit',NULL,0),
('Archive_Location','Notes','nvarchar',500,1),
('Auth_GeoRegion','RegionID','int',NULL,0),
('Auth_GeoRegion','GeoAuthCode','varchar',12,0),
('Auth_GeoRegion','RegionName','varchar',255,0),
('Auth_GeoRegion','RegionTypeID','int',NULL,0),
('Auth_GeoRegion','RegionFIPSCode','varchar',10,1),
('Auth_GeoRegion','ParentRegionID','int',NULL,1),
('Auth_GeoRegion_Type','RegionTypeID','int',NULL,0),
('Auth_GeoRegion_Type','RegionTypeName','varchar',50,0),
('SobekCM_Browse_Info_Statistics','BrowseInfoStatsID','int',NULL,0),
('SobekCM_Browse_Info_Statistics','AggregationID','int',NULL,1),
('SobekCM_Browse_Info_Statistics','BrowseInfoCode','varchar',150,0),
('SobekCM_Browse_Info_Statistics','Year','smallint',NULL,0),
('SobekCM_Browse_Info_Statistics','Month','smallint',NULL,0),
('SobekCM_Browse_Info_Statistics','Hits','int',NULL,0),
('SobekCM_Builder_Incoming_Folders','IncomingFolderId','int',NULL,0),
('SobekCM_Builder_Incoming_Folders','NetworkFolder','varchar',255,0),
('SobekCM_Builder_Incoming_Folders','ErrorFolder','varchar',255,0),
('SobekCM_Builder_Incoming_Folders','ProcessingFolder','varchar',255,0),
('SobekCM_Builder_Incoming_Folders','Perform_Checksum_Validation','bit',NULL,0),
('SobekCM_Builder_Incoming_Folders','Archive_TIFF','bit',NULL,0),
('SobekCM_Builder_Incoming_Folders','Archive_All_Files','bit',NULL,0),
('SobekCM_Builder_Incoming_Folders','Allow_Deletes','bit',NULL,0),
('SobekCM_Builder_Incoming_Folders','Allow_Folders_No_Metadata','bit',NULL,0),
('SobekCM_Builder_Incoming_Folders','Allow_Metadata_Updates','bit',NULL,0),
('SobekCM_Builder_Incoming_Folders','FolderName','nvarchar',150,0),
('SobekCM_Builder_Incoming_Folders','Can_Move_To_Content_Folder','bit',NULL,1),
('SobekCM_Builder_Incoming_Folders','BibID_Roots_Restrictions','varchar',255,0),
('SobekCM_Builder_Incoming_Folders','ModuleSetID','int',NULL,1),
('SobekCM_Builder_Log','BuilderLogID','bigint',NULL,0),
('SobekCM_Builder_Log','RelatedBuilderLogID','bigint',NULL,1),
('SobekCM_Builder_Log','LogDate','datetime',NULL,1),
('SobekCM_Builder_Log','BibID_VID','varchar',16,1),
('SobekCM_Builder_Log','LogType','varchar',25,1),
('SobekCM_Builder_Log','LogMessage','varchar',2000,1),
('SobekCM_Builder_Log','SuccessMessage','varchar',500,1),
('SobekCM_Builder_Log','METS_Type','varchar',50,1),
('SobekCM_Builder_Module','ModuleID','int',NULL,0),
('SobekCM_Builder_Module','ModuleSetID','int',NULL,0),
('SobekCM_Builder_Module','ModuleDesc','varchar',200,0),
('SobekCM_Builder_Module','Assembly','varchar',250,1),
('SobekCM_Builder_Module','Class','varchar',500,0),
('SobekCM_Builder_Module','Enabled','bit',NULL,0),
('SobekCM_Builder_Module','Order','int',NULL,0),
('SobekCM_Builder_Module','Argument1','varchar',-1,1),
('SobekCM_Builder_Module','Argument2','varchar',-1,1),
('SobekCM_Builder_Module','Argument3','varchar',-1,1),
('SobekCM_Builder_Module_Schedule','ModuleScheduleID','int',NULL,0),
('SobekCM_Builder_Module_Schedule','ModuleSetID','int',NULL,0),
('SobekCM_Builder_Module_Schedule','DaysOfWeek','varchar',7,0),
('SobekCM_Builder_Module_Schedule','Enabled','bit',NULL,0),
('SobekCM_Builder_Module_Schedule','TimesOfDay','varchar',100,0),
('SobekCM_Builder_Module_Schedule','Description','varchar',250,0),
('SobekCM_Builder_Module_Scheduled_Run','ModuleSchedRunID','int',NULL,0),
('SobekCM_Builder_Module_Scheduled_Run','ModuleScheduleID','int',NULL,0),
('SobekCM_Builder_Module_Scheduled_Run','Timestamp','datetime',NULL,0),
('SobekCM_Builder_Module_Scheduled_Run','Outcome','varchar',100,0),
('SobekCM_Builder_Module_Scheduled_Run','Message','varchar',-1,1),
('SobekCM_Builder_Module_Set','ModuleSetID','int',NULL,0),
('SobekCM_Builder_Module_Set','ModuleTypeID','int',NULL,0),
('SobekCM_Builder_Module_Set','SetName','varchar',50,0),
('SobekCM_Builder_Module_Set','SetOrder','int',NULL,0),
('SobekCM_Builder_Module_Set','Enabled','bit',NULL,0),
('SobekCM_Builder_Module_Type','ModuleTypeID','int',NULL,0),
('SobekCM_Builder_Module_Type','TypeAbbrev','varchar',4,0),
('SobekCM_Builder_Module_Type','TypeDescription','varchar',200,0),
('SobekCM_Database_Version','Major_Version','int',NULL,1),
('SobekCM_Database_Version','Minor_Version','int',NULL,1),
('SobekCM_Database_Version','Release_Phase','varchar',10,1),
('SobekCM_Email_Log','EmailID','int',NULL,0),
('SobekCM_Email_Log','Sender','varchar',255,0),
('SobekCM_Email_Log','Receipt_List','varchar',500,0),
('SobekCM_Email_Log','Subject_Line','varchar',500,0),
('SobekCM_Email_Log','Email_Body','varchar',-1,0),
('SobekCM_Email_Log','Sent_Date','datetime',NULL,0),
('SobekCM_Email_Log','HTML_Format','bit',NULL,0),
('SobekCM_Email_Log','Contact_Us','bit',NULL,0),
('SobekCM_Email_Log','ReplyToEmailId','int',NULL,1),
('SobekCM_Email_Log','UserID','int',NULL,1),
('SobekCM_Extension','ExtensionID','int',NULL,0),
('SobekCM_Extension','Code','nvarchar',50,0),
('SobekCM_Extension','Name','nvarchar',255,0),
('SobekCM_Extension','CurrentVersion','varchar',50,0),
('SobekCM_Extension','IsEnabled','bit',NULL,0),
('SobekCM_Extension','EnabledDate','datetime',NULL,1),
('SobekCM_Extension','LicenseKey','nvarchar',-1,1),
('SobekCM_Extension','UpgradeUrl','nvarchar',255,1),
('SobekCM_Extension','LatestVersion','varchar',50,1),
('SobekCM_External_Record_Type','ExtRecordTypeID','int',NULL,0),
('SobekCM_External_Record_Type','ExtRecordType','varchar',25,0),
('SobekCM_External_Record_Type','repeatableTypeFlag','bit',NULL,0),
('SobekCM_IP_Restriction_Range','IP_RangeID','int',NULL,0),
('SobekCM_IP_Restriction_Range','Title','nvarchar',150,0),
('SobekCM_IP_Restriction_Range','Notes','nvarchar',2000,0),
('SobekCM_IP_Restriction_Range','Not_Valid_Statement','nvarchar',-1,0),
('SobekCM_IP_Restriction_Range','Deleted','bit',NULL,0),
('SobekCM_IP_Restriction_Single','IP_SingleID','int',NULL,0),
('SobekCM_IP_Restriction_Single','IP_RangeID','int',NULL,0),
('SobekCM_IP_Restriction_Single','StartIP','char',15,0),
('SobekCM_IP_Restriction_Single','EndIP','char',15,1),
('SobekCM_IP_Restriction_Single','Notes','nvarchar',100,1),
('SobekCM_Icon','IconID','int',NULL,0),
('SobekCM_Icon','Icon_Name','varchar',255,0),
('SobekCM_Icon','Icon_URL','varchar',255,0),
('SobekCM_Icon','Link','varchar',255,1),
('SobekCM_Icon','Height','int',NULL,0),
('SobekCM_Icon','Title','varchar',255,1),
('SobekCM_Item','ItemID','int',NULL,0),
('SobekCM_Item','VID','varchar',5,0),
('SobekCM_Item','PageCount','int',NULL,0),
('SobekCM_Item','TextSearchable','bit',NULL,0),
('SobekCM_Item','AssocFilePath','varchar',50,1),
('SobekCM_Item','Deleted','bit',NULL,0),
('SobekCM_Item','Title','nvarchar',500,0),
('SobekCM_Item','AccessMethod','int',NULL,0),
('SobekCM_Item','Link','varchar',500,1),
('SobekCM_Item','CreateDate','datetime',NULL,1),
('SobekCM_Item','PubYear','int',NULL,1),
('SobekCM_Item','Locked','bit',NULL,0),
('SobekCM_Item','MainThumbnail','varchar',100,1),
('SobekCM_Item','MainJPEG','varchar',100,1),
('SobekCM_Item','PubDate','nvarchar',100,1),
('SobekCM_Item','SortDate','bigint',NULL,1),
('SobekCM_Item','Country','nvarchar',250,1),
('SobekCM_Item','State','nvarchar',250,1),
('SobekCM_Item','County','nvarchar',250,1),
('SobekCM_Item','City','nvarchar',250,1),
('SobekCM_Item','MainLatitude','varchar',25,1),
('SobekCM_Item','MainLongitude','varchar',25,1),
('SobekCM_Item','FileCount','int',NULL,0),
('SobekCM_Item','Format','varchar',100,0),
('SobekCM_Item','Donor','nvarchar',250,1),
('SobekCM_Item','Publisher','nvarchar',1000,1),
('SobekCM_Item','Author','nvarchar',1000,1),
('SobekCM_Item','Spatial_KML','varchar',4000,1),
('SobekCM_Item','GroupID','int',NULL,0),
('SobekCM_Item','Level1_Text','nvarchar',255,1),
('SobekCM_Item','Level1_Index','int',NULL,1),
('SobekCM_Item','Level2_Text','nvarchar',255,1),
('SobekCM_Item','Level2_Index','int',NULL,1),
('SobekCM_Item','Level3_Text','nvarchar',255,1),
('SobekCM_Item','Level3_Index','int',NULL,1),
('SobekCM_Item','Level4_Text','nvarchar',255,1),
('SobekCM_Item','Level4_Index','int',NULL,1),
('SobekCM_Item','Level5_Text','nvarchar',255,1),
('SobekCM_Item','Level5_Index','int',NULL,1),
('SobekCM_Item','CheckoutRequired','bit',NULL,0),
('SobekCM_Item','Spatial_KML_Distance','float',NULL,0),
('SobekCM_Item','DiskSize_KB','bigint',NULL,0),
('SobekCM_Item','IP_Restriction_Mask','smallint',NULL,0),
('SobekCM_Item','IncludeInAll','bit',NULL,0),
('SobekCM_Item','SuppressOAI','bit',NULL,0),
('SobekCM_Item','LastSaved','datetime',NULL,1),
('SobekCM_Item','VIDSource','varchar',150,1),
('SobekCM_Item','CreateYear','smallint',NULL,0),
('SobekCM_Item','CreateMonth','smallint',NULL,0),
('SobekCM_Item','Internal_Comments','nvarchar',1000,1),
('SobekCM_Item','TEMP_SourceCode','varchar',10,1),
('SobekCM_Item','TEMP_HoldingCode','varchar',10,1),
('SobekCM_Item','Dark','bit',NULL,0),
('SobekCM_Item','CopyrightIndicator','smallint',NULL,1),
('SobekCM_Item','VolumeID','int',NULL,0),
('SobekCM_Item','Last_MileStone','int',NULL,0),
('SobekCM_Item','Milestone_DigitalAcquisition','datetime',NULL,1),
('SobekCM_Item','Milestone_ImageProcessing','datetime',NULL,1),
('SobekCM_Item','Milestone_QualityControl','datetime',NULL,1),
('SobekCM_Item','Milestone_OnlineComplete','datetime',NULL,1),
('SobekCM_Item','Born_Digital','bit',NULL,0),
('SobekCM_Item','Material_Received_Date','datetime',NULL,1),
('SobekCM_Item','Disposition_Advice','int',NULL,1),
('SobekCM_Item','Disposition_Date','datetime',NULL,1),
('SobekCM_Item','Disposition_Type','int',NULL,1),
('SobekCM_Item','Locally_Archived','bit',NULL,0),
('SobekCM_Item','Remotely_Archived','bit',NULL,0),
('SobekCM_Item','Material_Recd_Date_Estimated','bit',NULL,0),
('SobekCM_Item','Tracking_Box','varchar',25,1),
('SobekCM_Item','AggregationCodes','varchar',100,1),
('SobekCM_Item','Left_To_Right','bit',NULL,0),
('SobekCM_Item','Disposition_Advice_Notes','varchar',150,0),
('SobekCM_Item','Disposition_Notes','varchar',150,0),
('SobekCM_Item','Spatial_Display','nvarchar',1000,1),
('SobekCM_Item','Institution_Display','nvarchar',1000,1),
('SobekCM_Item','Edition_Display','nvarchar',1000,1),
('SobekCM_Item','Material_Display','nvarchar',1000,1),
('SobekCM_Item','Measurement_Display','nvarchar',1000,1),
('SobekCM_Item','StylePeriod_Display','nvarchar',1000,1),
('SobekCM_Item','Technique_Display','nvarchar',1000,1),
('SobekCM_Item','Subjects_Display','nvarchar',1000,1),
('SobekCM_Item','AdditionalWorkNeeded','bit',NULL,0),
('SobekCM_Item','ExposeFullTextForHarvesting','bit',NULL,0),
('SobekCM_Item','Total_Hits','bigint',NULL,0),
('SobekCM_Item','Total_Sessions','bigint',NULL,0),
('SobekCM_Item','SortTitle','nvarchar',500,0),
('SobekCM_Item','TivoliSize_MB','bigint',NULL,0),
('SobekCM_Item','TivoliSize_Calculated','datetime',NULL,0),
('SobekCM_Item','metadataProfile','nvarchar',50,0),
('SobekCM_Item','COinS_OpenURL','varchar',-1,1),
('SobekCM_Item','Complete_KML','varchar',-1,1),
('SobekCM_Item','SpatialFootprint','varchar',255,1),
('SobekCM_Item','SpatialFootprintDistance','float',NULL,0),
('SobekCM_Item','CitationSet','varchar',50,1),
('SobekCM_Item','MadePublicDate','datetime',NULL,1),
('SobekCM_Item','RestrictionMessage','nvarchar',1024,1),
('SobekCM_Item_Aggregation','AggregationID','int',NULL,0),
('SobekCM_Item_Aggregation','Code','varchar',20,0),
('SobekCM_Item_Aggregation','Name','nvarchar',255,0),
('SobekCM_Item_Aggregation','ShortName','nvarchar',100,1),
('SobekCM_Item_Aggregation','Description','nvarchar',1000,1),
('SobekCM_Item_Aggregation','ThematicHeadingID','int',NULL,0),
('SobekCM_Item_Aggregation','Type','varchar',50,1),
('SobekCM_Item_Aggregation','isActive','bit',NULL,0),
('SobekCM_Item_Aggregation','Hidden','bit',NULL,0),
('SobekCM_Item_Aggregation','DisplayOptions','varchar',10,0),
('SobekCM_Item_Aggregation','Map_Search','tinyint',NULL,0),
('SobekCM_Item_Aggregation','Map_Display','tinyint',NULL,0),
('SobekCM_Item_Aggregation','OAI_Flag','bit',NULL,0),
('SobekCM_Item_Aggregation','OAI_Metadata','nvarchar',2000,1),
('SobekCM_Item_Aggregation','ContactEmail','varchar',255,0),
('SobekCM_Item_Aggregation','HasNewItems','bit',NULL,0),
('SobekCM_Item_Aggregation','DefaultInterface','varchar',50,0),
('SobekCM_Item_Aggregation','TEMP_OldID','int',NULL,1),
('SobekCM_Item_Aggregation','TEMP_OldType','varchar',2,1),
('SobekCM_Item_Aggregation','Items_Can_Be_Described','tinyint',NULL,0),
('SobekCM_Item_Aggregation','LastItemAdded','date',NULL,1),
('SobekCM_Item_Aggregation','External_Link','nvarchar',255,1),
('SobekCM_Item_Aggregation','DateAdded','datetime',NULL,0),
('SobekCM_Item_Aggregation','Can_Browse_Items','bit',NULL,0),
('SobekCM_Item_Aggregation','Include_In_Collection_Facet','bit',NULL,0),
('SobekCM_Item_Aggregation','Current_Item_Count','int',NULL,0),
('SobekCM_Item_Aggregation','Current_Title_Count','int',NULL,0),
('SobekCM_Item_Aggregation','Deleted','bit',NULL,0),
('SobekCM_Item_Aggregation','DeleteDate','date',NULL,1),
('SobekCM_Item_Aggregation','LanguageVariants','varchar',500,0),
('SobekCM_Item_Aggregation','GroupResults','bit',NULL,0),
('SobekCM_Item_Aggregation_Alias','AggregationAliasID','int',NULL,0),
('SobekCM_Item_Aggregation_Alias','AggregationAlias','varchar',50,0),
('SobekCM_Item_Aggregation_Alias','AggregationID','int',NULL,0),
('SobekCM_Item_Aggregation_Default_Result_Fields','ItemAggregationResultTypeID','int',NULL,0),
('SobekCM_Item_Aggregation_Default_Result_Fields','MetadataTypeID','smallint',NULL,0),
('SobekCM_Item_Aggregation_Default_Result_Fields','OverrideDisplayTerm','nvarchar',255,1),
('SobekCM_Item_Aggregation_Default_Result_Fields','DisplayOrder','int',NULL,0),
('SobekCM_Item_Aggregation_Default_Result_Fields','DisplayOptions','nvarchar',255,1),
('SobekCM_Item_Aggregation_Facets','AggregationID','int',NULL,0),
('SobekCM_Item_Aggregation_Facets','MetadataTypeID','smallint',NULL,0),
('SobekCM_Item_Aggregation_Facets','OverrideFacetTerm','nvarchar',100,1),
('SobekCM_Item_Aggregation_Facets','FacetOrder','int',NULL,0),
('SobekCM_Item_Aggregation_Facets','FacetOptions','nvarchar',2000,1),
('SobekCM_Item_Aggregation_Hierarchy','ParentID','int',NULL,0),
('SobekCM_Item_Aggregation_Hierarchy','ChildID','int',NULL,0),
('SobekCM_Item_Aggregation_Hierarchy','Search_Parent_Only','bit',NULL,0),
('SobekCM_Item_Aggregation_Item_Link','ItemID','int',NULL,0),
('SobekCM_Item_Aggregation_Item_Link','AggregationID','int',NULL,0),
('SobekCM_Item_Aggregation_Item_Link','impliedLink','bit',NULL,0),
('SobekCM_Item_Aggregation_Milestones','AggregationMilestoneID','int',NULL,0),
('SobekCM_Item_Aggregation_Milestones','AggregationID','int',NULL,0),
('SobekCM_Item_Aggregation_Milestones','Milestone','nvarchar',-1,0),
('SobekCM_Item_Aggregation_Milestones','MilestoneDate','date',NULL,0),
('SobekCM_Item_Aggregation_Milestones','MilestoneUser','nvarchar',100,0),
('SobekCM_Item_Aggregation_Result_Fields','ItemAggregationResultID','int',NULL,0),
('SobekCM_Item_Aggregation_Result_Fields','MetadataTypeID','smallint',NULL,0),
('SobekCM_Item_Aggregation_Result_Fields','OverrideDisplayTerm','nvarchar',255,1),
('SobekCM_Item_Aggregation_Result_Fields','DisplayOrder','int',NULL,0),
('SobekCM_Item_Aggregation_Result_Fields','DisplayOptions','nvarchar',2000,1),
('SobekCM_Item_Aggregation_Result_Types','ItemAggregationResultTypeID','int',NULL,0),
('SobekCM_Item_Aggregation_Result_Types','ResultType','varchar',50,0),
('SobekCM_Item_Aggregation_Result_Types','DefaultOrder','int',NULL,0),
('SobekCM_Item_Aggregation_Result_Types','DefaultView','bit',NULL,0),
('SobekCM_Item_Aggregation_Result_Views','ItemAggregationResultID','int',NULL,0),
('SobekCM_Item_Aggregation_Result_Views','AggregationID','int',NULL,0),
('SobekCM_Item_Aggregation_Result_Views','ItemAggregationResultTypeID','int',NULL,0),
('SobekCM_Item_Aggregation_Result_Views','DefaultView','bit',NULL,0),
('SobekCM_Item_Aggregation_Settings','AggregationSettingID','bigint',NULL,0),
('SobekCM_Item_Aggregation_Settings','AggregationID','int',NULL,0),
('SobekCM_Item_Aggregation_Settings','Setting_Key','nvarchar',255,0),
('SobekCM_Item_Aggregation_Settings','Setting_Value','nvarchar',-1,0),
('SobekCM_Item_Aggregation_Statistics','AggregationStatsID','int',NULL,0),
('SobekCM_Item_Aggregation_Statistics','AggregationID','int',NULL,0),
('SobekCM_Item_Aggregation_Statistics','Year','smallint',NULL,0),
('SobekCM_Item_Aggregation_Statistics','Month','smallint',NULL,0),
('SobekCM_Item_Aggregation_Statistics','Hits','int',NULL,0),
('SobekCM_Item_Aggregation_Statistics','Sessions','int',NULL,0),
('SobekCM_Item_Aggregation_Statistics','Home_Page_Views','int',NULL,0),
('SobekCM_Item_Aggregation_Statistics','Browse_Views','int',NULL,0),
('SobekCM_Item_Aggregation_Statistics','Advanced_Search_Views','int',NULL,0),
('SobekCM_Item_Aggregation_Statistics','Search_Results_Views','int',NULL,0),
('SobekCM_Item_Aggregation_Statistics','Title_Hits','int',NULL,1),
('SobekCM_Item_Aggregation_Statistics','Item_Hits','int',NULL,1),
('SobekCM_Item_Aggregation_Statistics','Item_JPEG_Views','int',NULL,1),
('SobekCM_Item_Aggregation_Statistics','Item_Zoomable_Views','int',NULL,1),
('SobekCM_Item_Aggregation_Statistics','Item_Citation_Views','int',NULL,1),
('SobekCM_Item_Aggregation_Statistics','Item_Thumbnail_Views','int',NULL,1),
('SobekCM_Item_Aggregation_Statistics','Item_Text_Search_Views','int',NULL,1),
('SobekCM_Item_Aggregation_Statistics','Item_Flash_Views','int',NULL,1),
('SobekCM_Item_Aggregation_Statistics','Item_Google_Map_Views','int',NULL,1),
('SobekCM_Item_Aggregation_Statistics','Item_Download_Views','int',NULL,1),
('SobekCM_Item_Aggregation_Statistics','Item_Static_Views','int',NULL,1),
('SobekCM_Item_Aggregation_Statistics','Title_Count','int',NULL,1),
('SobekCM_Item_Aggregation_Statistics','Item_Count','int',NULL,1),
('SobekCM_Item_Alias','ItemAliasID','int',NULL,0),
('SobekCM_Item_Alias','Alias','varchar',50,0),
('SobekCM_Item_Alias','ItemID','int',NULL,0),
('SobekCM_Item_Error_Log','ItemErrorID','int',NULL,0),
('SobekCM_Item_Error_Log','BibID','varchar',50,0),
('SobekCM_Item_Error_Log','VID','varchar',5,0),
('SobekCM_Item_Error_Log','ErrorDescription','varchar',1000,0),
('SobekCM_Item_Error_Log','Date','datetime',NULL,0),
('SobekCM_Item_Error_Log','METS_Type','varchar',20,1),
('SobekCM_Item_Error_Log','ClearedBy','varchar',100,1),
('SobekCM_Item_Error_Log','ClearedDate','datetime',NULL,1),
('SobekCM_Item_Footprint','ItemGeoID','int',NULL,0),
('SobekCM_Item_Footprint','ItemID','int',NULL,0),
('SobekCM_Item_Footprint','Point_Latitude','float',NULL,1),
('SobekCM_Item_Footprint','Point_Longitude','float',NULL,1),
('SobekCM_Item_Footprint','Rect_Latitude_A','float',NULL,1),
('SobekCM_Item_Footprint','Rect_Longitude_A','float',NULL,1),
('SobekCM_Item_Footprint','Rect_Latitude_B','float',NULL,1),
('SobekCM_Item_Footprint','Rect_Longitude_B','float',NULL,1),
('SobekCM_Item_Footprint','Segment_KML','varchar',-1,1),
('SobekCM_Item_GeoRegion_Link','ItemID','int',NULL,0),
('SobekCM_Item_GeoRegion_Link','RegionID','int',NULL,0),
('SobekCM_Item_Group','GroupID','int',NULL,0),
('SobekCM_Item_Group','GroupTitle','nvarchar',1000,1),
('SobekCM_Item_Group','BibID','varchar',10,0),
('SobekCM_Item_Group','Deleted','bit',NULL,0),
('SobekCM_Item_Group','Type','varchar',50,0),
('SobekCM_Item_Group','SortTitle','nvarchar',1000,0),
('SobekCM_Item_Group','ItemCount','int',NULL,0),
('SobekCM_Item_Group','SuppressEndeca','bit',NULL,0),
('SobekCM_Item_Group','File_Root','varchar',100,0),
('SobekCM_Item_Group','GroupCreateDate','datetime',NULL,0),
('SobekCM_Item_Group','File_Location','varchar',100,1),
('SobekCM_Item_Group','OCLC','varchar',13,0),
('SobekCM_Item_Group','ALEPH','varchar',9,0),
('SobekCM_Item_Group','OCLC_Number','bigint',NULL,0),
('SobekCM_Item_Group','ALEPH_Number','int',NULL,0),
('SobekCM_Item_Group','GroupThumbnail','varchar',500,1),
('SobekCM_Item_Group','Internal_Comments','nvarchar',1000,1),
('SobekCM_Item_Group','Bib_Source','varchar',255,1),
('SobekCM_Item_Group','TEMP_ReceivingID','int',NULL,0),
('SobekCM_Item_Group','Track_By_Month','bit',NULL,0),
('SobekCM_Item_Group','Large_Format','bit',NULL,0),
('SobekCM_Item_Group','Never_Overlay_Record','bit',NULL,0),
('SobekCM_Item_Group','Include_In_MarcXML_Prod_Feed','bit',NULL,0),
('SobekCM_Item_Group','Include_In_MarcXML_Test_Feed','bit',NULL,0),
('SobekCM_Item_Group','Suppress_OAI','bit',NULL,0),
('SobekCM_Item_Group','Primary_Identifier_Type','nvarchar',50,1),
('SobekCM_Item_Group','Primary_Identifier','nvarchar',100,1),
('SobekCM_Item_Group','HasGroupMetadata','bit',NULL,0),
('SobekCM_Item_Group','CustomThumbnail','nvarchar',255,1),
('SobekCM_Item_Group','ThumbnailType','tinyint',NULL,0),
('SobekCM_Item_Group','FlagByte','tinyint',NULL,0),
('SobekCM_Item_Group','LastFourInt','smallint',NULL,1),
('SobekCM_Item_Group_External_Record','ExtRecordLinkID','int',NULL,0),
('SobekCM_Item_Group_External_Record','GroupID','int',NULL,0),
('SobekCM_Item_Group_External_Record','ExtRecordTypeID','int',NULL,0),
('SobekCM_Item_Group_External_Record','ExtRecordValue','varchar',50,0),
('SobekCM_Item_Group_OAI','GroupID','int',NULL,0),
('SobekCM_Item_Group_OAI','OAI_Data','nvarchar',-1,0),
('SobekCM_Item_Group_OAI','Locked','bit',NULL,0),
('SobekCM_Item_Group_OAI','OAI_Date','date',NULL,1),
('SobekCM_Item_Group_OAI','Data_Code','varchar',20,0),
('SobekCM_Item_Group_Relationship','GroupA','int',NULL,0),
('SobekCM_Item_Group_Relationship','GroupB','int',NULL,0),
('SobekCM_Item_Group_Relationship','Relationship_A_to_B','nvarchar',100,0),
('SobekCM_Item_Group_Relationship','Relationship_B_to_A','nvarchar',100,0),
('SobekCM_Item_Group_Statistics','ItemGroupStatsID','int',NULL,0),
('SobekCM_Item_Group_Statistics','GroupID','int',NULL,0),
('SobekCM_Item_Group_Statistics','Year','smallint',NULL,0),
('SobekCM_Item_Group_Statistics','Month','smallint',NULL,0),
('SobekCM_Item_Group_Statistics','Hits','int',NULL,1),
('SobekCM_Item_Group_Statistics','Sessions','int',NULL,0),
('SobekCM_Item_Group_Viewer_Types','ItemGroupViewTypeID','int',NULL,0),
('SobekCM_Item_Group_Viewer_Types','ViewType','varchar',50,0),
('SobekCM_Item_Group_Viewers','ItemGroupViewID','int',NULL,0),
('SobekCM_Item_Group_Viewers','GroupID','int',NULL,0),
('SobekCM_Item_Group_Viewers','ItemGroupViewTypeID','int',NULL,0),
('SobekCM_Item_Group_Viewers','Attribute','nvarchar',250,0),
('SobekCM_Item_Group_Viewers','Label','nvarchar',50,0),
('SobekCM_Item_Group_Web_Skin_Link','WebSkinID','int',NULL,0),
('SobekCM_Item_Group_Web_Skin_Link','GroupID','int',NULL,0),
('SobekCM_Item_Group_Web_Skin_Link','Sequence','int',NULL,0),
('SobekCM_Item_Icons','ItemID','int',NULL,0),
('SobekCM_Item_Icons','IconID','int',NULL,0),
('SobekCM_Item_Icons','Sequence','int',NULL,0),
('SobekCM_Item_OAI','ItemID','int',NULL,0),
('SobekCM_Item_OAI','OAI_Data','nvarchar',-1,0),
('SobekCM_Item_OAI','Locked','bit',NULL,0),
('SobekCM_Item_OAI','OAI_Date','date',NULL,1),
('SobekCM_Item_OAI','Data_Code','varchar',20,0),
('SobekCM_Item_Settings','ItemSettingID','bigint',NULL,0),
('SobekCM_Item_Settings','ItemID','int',NULL,0),
('SobekCM_Item_Settings','Setting_Key','nvarchar',255,0),
('SobekCM_Item_Settings','Setting_Value','nvarchar',-1,0),
('SobekCM_Item_Statistics','ItemStatsID','int',NULL,0),
('SobekCM_Item_Statistics','ItemID','int',NULL,0),
('SobekCM_Item_Statistics','Year','smallint',NULL,0),
('SobekCM_Item_Statistics','Month','smallint',NULL,0),
('SobekCM_Item_Statistics','Hits','int',NULL,0),
('SobekCM_Item_Statistics','Sessions','int',NULL,0),
('SobekCM_Item_Statistics','JPEG_Views','int',NULL,0),
('SobekCM_Item_Statistics','Zoomable_Views','int',NULL,0),
('SobekCM_Item_Statistics','Citation_Views','int',NULL,0),
('SobekCM_Item_Statistics','Thumbnail_Views','int',NULL,0),
('SobekCM_Item_Statistics','Text_Search_Views','int',NULL,0),
('SobekCM_Item_Statistics','Flash_Views','int',NULL,0),
('SobekCM_Item_Statistics','Google_Map_Views','int',NULL,0),
('SobekCM_Item_Statistics','Download_Views','int',NULL,0),
('SobekCM_Item_Statistics','Static_Views','int',NULL,0),
('SobekCM_Item_Viewer_Types','ItemViewTypeID','int',NULL,0),
('SobekCM_Item_Viewer_Types','ViewType','varchar',50,0),
('SobekCM_Item_Viewer_Types','Order','int',NULL,0),
('SobekCM_Item_Viewer_Types','DefaultView','bit',NULL,0),
('SobekCM_Item_Viewer_Types','MenuOrder','float',NULL,0),
('SobekCM_Item_Viewers','ItemViewID','int',NULL,0),
('SobekCM_Item_Viewers','ItemID','int',NULL,0),
('SobekCM_Item_Viewers','ItemViewTypeID','int',NULL,0),
('SobekCM_Item_Viewers','Attribute','nvarchar',250,0),
('SobekCM_Item_Viewers','Label','nvarchar',50,0),
('SobekCM_Item_Viewers','OrderOverride','int',NULL,1),
('SobekCM_Item_Viewers','Exclude','bit',NULL,0),
('SobekCM_Item_Viewers','MenuOrder','float',NULL,1),
('SobekCM_Metadata_Translation','TranslationID','int',NULL,0),
('SobekCM_Metadata_Translation','English','varchar',50,0),
('SobekCM_Metadata_Translation','French','varchar',50,0),
('SobekCM_Metadata_Translation','Spanish','varchar',50,0),
('SobekCM_Metadata_Types','MetadataTypeID','smallint',NULL,0),
('SobekCM_Metadata_Types','MetadataName','varchar',100,0),
('SobekCM_Metadata_Types','SobekCode','char',2,1),
('SobekCM_Metadata_Types','SolrCode','varchar',100,1),
('SobekCM_Metadata_Types','DisplayTerm','nvarchar',100,1),
('SobekCM_Metadata_Types','FacetTerm','varchar',100,1),
('SobekCM_Metadata_Types','CustomField','bit',NULL,0),
('SobekCM_Metadata_Types','canFacetBrowse','bit',NULL,0),
('SobekCM_Metadata_Types','DefaultAdvancedSearch','bit',NULL,0),
('SobekCM_Metadata_Types','LegacySolrCode','varchar',100,1),
('SobekCM_Metadata_Types','SolrCode_Facets','varchar',100,1),
('SobekCM_Metadata_Types','SolrCode_Display','varchar',100,1),
('SobekCM_Mime_Types','MimeTypeID','int',NULL,0),
('SobekCM_Mime_Types','Extension','varchar',20,0),
('SobekCM_Mime_Types','MimeType','varchar',100,0),
('SobekCM_Mime_Types','isBlocked','bit',NULL,0),
('SobekCM_Mime_Types','shouldForward','bit',NULL,0),
('SobekCM_OpenPublishing_Theme','ThemeID','int',NULL,0),
('SobekCM_OpenPublishing_Theme','ThemeName','nvarchar',150,0),
('SobekCM_OpenPublishing_Theme','Location','varchar',255,0),
('SobekCM_OpenPublishing_Theme','Author','nvarchar',50,1),
('SobekCM_OpenPublishing_Theme','Description','nvarchar',1000,1),
('SobekCM_OpenPublishing_Theme','Image','nvarchar',255,1),
('SobekCM_OpenPublishing_Theme','AvailableForSelection','bit',NULL,0),
('SobekCM_OpenPublishing_Theme','Default','bit',NULL,0),
('SobekCM_Portal_Item_Aggregation_Link','PortalID','int',NULL,0),
('SobekCM_Portal_Item_Aggregation_Link','AggregationID','int',NULL,0),
('SobekCM_Portal_Item_Aggregation_Link','isDefault','bit',NULL,0),
('SobekCM_Portal_URL','PortalID','int',NULL,0),
('SobekCM_Portal_URL','Base_URL','varchar',150,0),
('SobekCM_Portal_URL','isActive','bit',NULL,0),
('SobekCM_Portal_URL','isDefault','bit',NULL,0),
('SobekCM_Portal_URL','Abbreviation','nvarchar',10,0),
('SobekCM_Portal_URL','Name','nvarchar',250,0),
('SobekCM_Portal_URL','Base_PURL','nvarchar',150,1),
('SobekCM_Portal_URL_Statistics','PortalStatsID','int',NULL,0),
('SobekCM_Portal_URL_Statistics','PortalID','int',NULL,0),
('SobekCM_Portal_URL_Statistics','Year','smallint',NULL,0),
('SobekCM_Portal_URL_Statistics','Month','smallint',NULL,0),
('SobekCM_Portal_URL_Statistics','Hits','int',NULL,0),
('SobekCM_Portal_Web_Skin_Link','PortalID','int',NULL,0),
('SobekCM_Portal_Web_Skin_Link','WebSkinID','int',NULL,0),
('SobekCM_Portal_Web_Skin_Link','isDefault','bit',NULL,0),
('SobekCM_Project','ProjectID','int',NULL,0),
('SobekCM_Project','ProjectCode','nvarchar',20,1),
('SobekCM_Project','ProjectName','nvarchar',100,0),
('SobekCM_Project','ProjectManager','nvarchar',100,1),
('SobekCM_Project','GrantID','nvarchar',20,1),
('SobekCM_Project','GrantName','nvarchar',250,1),
('SobekCM_Project','StartDate','date',NULL,1),
('SobekCM_Project','EndDate','date',NULL,1),
('SobekCM_Project','isActive','bit',NULL,1),
('SobekCM_Project','Description','nvarchar',1000,1),
('SobekCM_Project','Specifications','nvarchar',1000,1),
('SobekCM_Project','Priority','nvarchar',100,1),
('SobekCM_Project','QC_Profile','nvarchar',100,1),
('SobekCM_Project','TargetItemCount','int',NULL,1),
('SobekCM_Project','TargetPageCount','int',NULL,1),
('SobekCM_Project','Comments','nvarchar',1000,1),
('SobekCM_Project','CopyrightPermissions','nvarchar',1000,1),
('SobekCM_Project_Aggregation_Link','ProjectID','int',NULL,0),
('SobekCM_Project_Aggregation_Link','AggregationID','int',NULL,0),
('SobekCM_Project_DefaultMetadata_Link','ProjectID','int',NULL,0),
('SobekCM_Project_DefaultMetadata_Link','DefaultMetadataID','int',NULL,0),
('SobekCM_Project_Item_Link','ProjectID','int',NULL,0),
('SobekCM_Project_Item_Link','ItemID','int',NULL,0),
('SobekCM_Project_Template_Link','ProjectID','int',NULL,0),
('SobekCM_Project_Template_Link','TemplateID','int',NULL,0),
('SobekCM_QC_Errors','ErrorID','bigint',NULL,0),
('SobekCM_QC_Errors','ItemID','int',NULL,0),
('SobekCM_QC_Errors','FileName','nvarchar',-1,0),
('SobekCM_QC_Errors','ErrorCode','nchar',10,0),
('SobekCM_QC_Errors','isVolumeError','bit',NULL,1),
('SobekCM_QC_Errors','Description','nvarchar',-1,1),
('SobekCM_QC_Errors_History','ErrorID','bigint',NULL,0),
('SobekCM_QC_Errors_History','ItemID','int',NULL,0),
('SobekCM_QC_Errors_History','ErrorCode','nchar',10,0),
('SobekCM_QC_Errors_History','isVolumeError','bit',NULL,1),
('SobekCM_QC_Errors_History','Count','int',NULL,0),
('SobekCM_Search_Stop_Words','StopWordId','int',NULL,0),
('SobekCM_Search_Stop_Words','StopWord','nvarchar',50,0),
('SobekCM_Settings','Setting_Key','varchar',255,0),
('SobekCM_Settings','Setting_Value','varchar',-1,0),
('SobekCM_Settings','TabPage','nvarchar',75,1),
('SobekCM_Settings','Heading','nvarchar',75,1),
('SobekCM_Settings','Hidden','bit',NULL,0),
('SobekCM_Settings','Reserved','smallint',NULL,0),
('SobekCM_Settings','Help','varchar',-1,1),
('SobekCM_Settings','Options','varchar',-1,1),
('SobekCM_Settings','SettingID','int',NULL,0),
('SobekCM_Settings','Dimensions','varchar',100,1),
('SobekCM_Source_Line','SourceLineID','int',NULL,0),
('SobekCM_Source_Line','SourceLine','varchar',500,1),
('SobekCM_Source_Line','ItemID','int',NULL,1),
('SobekCM_Source_Line','PageSequence','int',NULL,1),
('SobekCM_Statistics','StatisticsID','int',NULL,0),
('SobekCM_Statistics','Year','smallint',NULL,0),
('SobekCM_Statistics','Month','smallint',NULL,0),
('SobekCM_Statistics','Hits','int',NULL,0),
('SobekCM_Statistics','Sessions','int',NULL,0),
('SobekCM_Statistics','Robot_Hits','int',NULL,0),
('SobekCM_Statistics','XML_Hits','int',NULL,0),
('SobekCM_Statistics','OAI_Hits','int',NULL,0),
('SobekCM_Statistics','JSON_Hits','int',NULL,0),
('SobekCM_Statistics','Aggregate_Statistics_Complete','bit',NULL,0),
('SobekCM_Thematic_Heading','ThematicHeadingID','int',NULL,0),
('SobekCM_Thematic_Heading','ThemeOrder','int',NULL,0),
('SobekCM_Thematic_Heading','ThemeName','nvarchar',100,0),
('SobekCM_WebContent','WebContentID','int',NULL,0),
('SobekCM_WebContent','Level1','varchar',100,0),
('SobekCM_WebContent','Level2','varchar',100,1),
('SobekCM_WebContent','Level3','varchar',100,1),
('SobekCM_WebContent','Level4','varchar',100,1),
('SobekCM_WebContent','Level5','varchar',100,1),
('SobekCM_WebContent','Level6','varchar',100,1),
('SobekCM_WebContent','Level7','varchar',100,1),
('SobekCM_WebContent','Level8','varchar',100,1),
('SobekCM_WebContent','Deleted','bit',NULL,0),
('SobekCM_WebContent','Title','nvarchar',255,1),
('SobekCM_WebContent','Summary','nvarchar',1000,1),
('SobekCM_WebContent','Redirect','nvarchar',500,1),
('SobekCM_WebContent','Locked','bit',NULL,0),
('SobekCM_WebContent_Milestones','WebContentMilestoneID','int',NULL,0),
('SobekCM_WebContent_Milestones','WebContentID','int',NULL,0),
('SobekCM_WebContent_Milestones','Milestone','nvarchar',-1,0),
('SobekCM_WebContent_Milestones','MilestoneDate','datetime',NULL,0),
('SobekCM_WebContent_Milestones','MilestoneUser','nvarchar',100,0),
('SobekCM_WebContent_Statistics','Level1','varchar',100,0),
('SobekCM_WebContent_Statistics','Level2','varchar',100,1),
('SobekCM_WebContent_Statistics','Level3','varchar',100,1),
('SobekCM_WebContent_Statistics','Level4','varchar',100,1),
('SobekCM_WebContent_Statistics','Level5','varchar',100,1),
('SobekCM_WebContent_Statistics','Level6','varchar',100,1),
('SobekCM_WebContent_Statistics','Level7','varchar',100,1),
('SobekCM_WebContent_Statistics','Level8','varchar',100,1),
('SobekCM_WebContent_Statistics','Year','smallint',NULL,0),
('SobekCM_WebContent_Statistics','Month','smallint',NULL,0),
('SobekCM_WebContent_Statistics','Hits','int',NULL,0),
('SobekCM_WebContent_Statistics','Hits_Complete','int',NULL,0),
('SobekCM_WebContent_Statistics','WebContentID','int',NULL,1),
('SobekCM_Web_Skin','WebSkinID','int',NULL,0),
('SobekCM_Web_Skin','WebSkinCode','varchar',20,0),
('SobekCM_Web_Skin','OverrideHeaderFooter','bit',NULL,1),
('SobekCM_Web_Skin','OverrideBanner','bit',NULL,1),
('SobekCM_Web_Skin','BannerLink','varchar',255,1),
('SobekCM_Web_Skin','BaseWebSkin','varchar',20,1),
('SobekCM_Web_Skin','Notes','varchar',250,1),
('SobekCM_Web_Skin','OldInterfaceID','int',NULL,1),
('SobekCM_Web_Skin','Build_On_Launch','bit',NULL,0),
('SobekCM_Web_Skin','SuppressTopNavigation','bit',NULL,0),
('Tracking_Disposition_Type','DispositionID','int',NULL,0),
('Tracking_Disposition_Type','DispositionFuture','varchar',100,0),
('Tracking_Disposition_Type','DispositionPast','varchar',100,0),
('Tracking_Disposition_Type','DispositionNotes','varchar',1000,0),
('Tracking_Item','ItemID','int',NULL,0),
('Tracking_Item','Original_AccessCode','varchar',25,1),
('Tracking_Item','EmbargoEnd','date',NULL,1),
('Tracking_Item','Original_EmbargoEnd','date',NULL,1),
('Tracking_Item','UMI','varchar',20,1),
('Tracking_Progress','ProgressID','int',NULL,0),
('Tracking_Progress','ItemID','int',NULL,0),
('Tracking_Progress','WorkFlowID','int',NULL,0),
('Tracking_Progress','DateCompleted','datetime',NULL,1),
('Tracking_Progress','WorkPerformedBy','varchar',255,1),
('Tracking_Progress','WorkingFilePath','varchar',255,1),
('Tracking_Progress','ProgressNote','varchar',1000,1),
('Tracking_Progress','DateStarted','datetime',NULL,1),
('Tracking_Progress','Duration','int',NULL,0),
('Tracking_Progress','RelatedEquipment','varchar',255,1),
('Tracking_Progress','Start_Event_Number','int',NULL,1),
('Tracking_Progress','End_Event_Number','int',NULL,1),
('Tracking_Progress','Start_And_End_Event_Number','int',NULL,1),
('Tracking_Progress','WorkPerformedById','int',NULL,1),
('Tracking_ScanningEquipment','EquipmentID','int',NULL,0),
('Tracking_ScanningEquipment','ScanningEquipment','nvarchar',255,0),
('Tracking_ScanningEquipment','Notes','nvarchar',-1,1),
('Tracking_ScanningEquipment','Location','nvarchar',255,1),
('Tracking_ScanningEquipment','EquipmentType','nvarchar',255,1),
('Tracking_ScanningEquipment','isActive','bit',NULL,0),
('Tracking_ScanningEquipment','ProductionStartDate','date',NULL,1),
('Tracking_ScanningEquipment','ProductionEndDate','date',NULL,1),
('Tracking_WorkFlow','WorkFlowID','int',NULL,0),
('Tracking_WorkFlow','WorkFlowName','varchar',100,0),
('Tracking_WorkFlow','WorkFlowNotes','varchar',1000,1),
('Tracking_WorkFlow','Start_Event_Number','int',NULL,1),
('Tracking_WorkFlow','End_Event_Number','int',NULL,1),
('Tracking_WorkFlow','Start_And_End_Event_Number','int',NULL,1),
('Tracking_WorkFlow','Start_Event_Desc','nvarchar',100,1),
('Tracking_WorkFlow','End_Event_Desc','nvarchar',100,1),
('mySobek_DefaultMetadata','DefaultMetadataID','int',NULL,0),
('mySobek_DefaultMetadata','MetadataName','varchar',100,0),
('mySobek_DefaultMetadata','MetadataCode','varchar',20,0),
('mySobek_DefaultMetadata','UserID','int',NULL,1),
('mySobek_DefaultMetadata','Description','varchar',255,0),
('mySobek_Editable_Regex','EditableID','int',NULL,0),
('mySobek_Editable_Regex','Editable_Name','varchar',250,0),
('mySobek_Editable_Regex','EditableRegex','varchar',-1,0),
('mySobek_Template','TemplateID','int',NULL,0),
('mySobek_Template','TemplateName','varchar',100,0),
('mySobek_Template','TemplateCode','varchar',20,0),
('mySobek_Template','Description','varchar',255,0),
('mySobek_User','UserID','int',NULL,0),
('mySobek_User','ShibbID','char',8,1),
('mySobek_User','UserName','nvarchar',100,1),
('mySobek_User','Password','nvarchar',100,1),
('mySobek_User','EmailAddress','varchar',100,1),
('mySobek_User','FirstName','nvarchar',100,1),
('mySobek_User','LastName','nvarchar',100,1),
('mySobek_User','DateCreated','datetime',NULL,0),
('mySobek_User','LastActivity','datetime',NULL,0),
('mySobek_User','isActive','bit',NULL,0),
('mySobek_User','Note_Length','int',NULL,0),
('mySobek_User','Can_Make_Folders_Public','bit',NULL,0),
('mySobek_User','isTemporary_Password','bit',NULL,0),
('mySobek_User','sendEmailOnSubmission','bit',NULL,0),
('mySobek_User','Can_Submit_Items','bit',NULL,0),
('mySobek_User','Lock_Out_Count','int',NULL,1),
('mySobek_User','Lock_Out_Date','datetime',NULL,1),
('mySobek_User','NickName','nvarchar',100,1),
('mySobek_User','Organization','nvarchar',250,1),
('mySobek_User','College','nvarchar',250,1),
('mySobek_User','Department','nvarchar',250,1),
('mySobek_User','Unit','nvarchar',250,1),
('mySobek_User','Default_Rights','nvarchar',1000,1),
('mySobek_User','UI_Language','nvarchar',50,1),
('mySobek_User','Internal_User','bit',NULL,0),
('mySobek_User','OrganizationCode','varchar',15,0),
('mySobek_User','EditTemplate','varchar',20,0),
('mySobek_User','EditTemplateMarc','varchar',20,0),
('mySobek_User','Receive_Stats_Emails','bit',NULL,0),
('mySobek_User','Has_Item_Stats','bit',NULL,0),
('mySobek_User','IsSystemAdmin','bit',NULL,0),
('mySobek_User','IsPortalAdmin','bit',NULL,0),
('mySobek_User','Include_Tracking_Standard_Forms','bit',NULL,0),
('mySobek_User','qcProfile','nvarchar',50,0),
('mySobek_User','Can_Delete_All_Items','bit',NULL,0),
('mySobek_User','ScanningTechnician','bit',NULL,0),
('mySobek_User','ProcessingTechnician','bit',NULL,0),
('mySobek_User','InternalNotes','nvarchar',500,1),
('mySobek_User','IsHostAdmin','bit',NULL,0),
('mySobek_User','IsUserAdmin','bit',NULL,0),
('mySobek_User','ExternalProviderCode','nvarchar',50,1),
('mySobek_User','ExternalSubjectId','nvarchar',450,1),
('mySobek_User_Bib_Link','UserID','int',NULL,0),
('mySobek_User_Bib_Link','GroupID','int',NULL,0),
('mySobek_User_DefaultMetadata_Link','UserID','int',NULL,0),
('mySobek_User_DefaultMetadata_Link','DefaultMetadataID','int',NULL,0),
('mySobek_User_DefaultMetadata_Link','CurrentlySelected','bit',NULL,0),
('mySobek_User_Description_Tags','TagID','int',NULL,0),
('mySobek_User_Description_Tags','UserID','int',NULL,0),
('mySobek_User_Description_Tags','Description_Tag','nvarchar',2000,0),
('mySobek_User_Description_Tags','Date_Modified','datetime',NULL,0),
('mySobek_User_Description_Tags','ItemID','int',NULL,0),
('mySobek_User_Edit_Aggregation','UserID','int',NULL,0),
('mySobek_User_Edit_Aggregation','AggregationID','int',NULL,0),
('mySobek_User_Edit_Aggregation','CanSelect','bit',NULL,0),
('mySobek_User_Edit_Aggregation','CanEditItems','bit',NULL,0),
('mySobek_User_Edit_Aggregation','OnHomePage','bit',NULL,0),
('mySobek_User_Edit_Aggregation','IsCurator','bit',NULL,0),
('mySobek_User_Edit_Aggregation','IsAdmin','bit',NULL,0),
('mySobek_User_Edit_Aggregation','CanEditMetadata','bit',NULL,0),
('mySobek_User_Edit_Aggregation','CanEditBehaviors','bit',NULL,0),
('mySobek_User_Edit_Aggregation','CanPerformQc','bit',NULL,0),
('mySobek_User_Edit_Aggregation','CanUploadFiles','bit',NULL,0),
('mySobek_User_Edit_Aggregation','CanChangeVisibility','bit',NULL,0),
('mySobek_User_Edit_Aggregation','CanDelete','bit',NULL,0),
('mySobek_User_Editable_Link','UserID','int',NULL,0),
('mySobek_User_Editable_Link','EditableID','int',NULL,0),
('mySobek_User_Editable_Link','CanEditMetadata','bit',NULL,0),
('mySobek_User_Editable_Link','CanEditBehaviors','bit',NULL,0),
('mySobek_User_Editable_Link','CanPerformQc','bit',NULL,0),
('mySobek_User_Editable_Link','CanUploadFiles','bit',NULL,0),
('mySobek_User_Editable_Link','CanChangeVisibility','bit',NULL,0),
('mySobek_User_Editable_Link','CanDelete','bit',NULL,0),
('mySobek_User_Folder','UserFolderID','int',NULL,0),
('mySobek_User_Folder','ParentFolderID','int',NULL,1),
('mySobek_User_Folder','UserID','int',NULL,0),
('mySobek_User_Folder','FolderName','nvarchar',255,0),
('mySobek_User_Folder','isPublic','bit',NULL,0),
('mySobek_User_Folder','FolderDescription','nvarchar',4000,0),
('mySobek_User_Group','UserGroupID','int',NULL,0),
('mySobek_User_Group','GroupName','nvarchar',150,0),
('mySobek_User_Group','GroupDescription','nvarchar',1000,0),
('mySobek_User_Group','Can_Submit_Items','bit',NULL,0),
('mySobek_User_Group','Internal_User','bit',NULL,0),
('mySobek_User_Group','IsSystemAdmin','bit',NULL,0),
('mySobek_User_Group','IsPortalAdmin','bit',NULL,0),
('mySobek_User_Group','Include_Tracking_Standard_Forms','bit',NULL,0),
('mySobek_User_Group','autoAssignUsers','bit',NULL,0),
('mySobek_User_Group','Can_Delete_All_Items','bit',NULL,0),
('mySobek_User_Group','IsSobekDefault','bit',NULL,0),
('mySobek_User_Group','IsShibbolethDefault','bit',NULL,0),
('mySobek_User_Group','IsLdapDefault','bit',NULL,0),
('mySobek_User_Group','IsSpecialGroup','bit',NULL,0),
('mySobek_User_Group_DefaultMetadata_Link','UserGroupID','int',NULL,0),
('mySobek_User_Group_DefaultMetadata_Link','DefaultMetadataID','int',NULL,0),
('mySobek_User_Group_Edit_Aggregation','UserGroupID','int',NULL,0),
('mySobek_User_Group_Edit_Aggregation','AggregationID','int',NULL,0),
('mySobek_User_Group_Edit_Aggregation','CanSelect','bit',NULL,0),
('mySobek_User_Group_Edit_Aggregation','CanEditItems','bit',NULL,0),
('mySobek_User_Group_Edit_Aggregation','IsCurator','bit',NULL,0),
('mySobek_User_Group_Edit_Aggregation','IsAdmin','bit',NULL,0),
('mySobek_User_Group_Edit_Aggregation','CanEditMetadata','bit',NULL,0),
('mySobek_User_Group_Edit_Aggregation','CanEditBehaviors','bit',NULL,0),
('mySobek_User_Group_Edit_Aggregation','CanPerformQc','bit',NULL,0),
('mySobek_User_Group_Edit_Aggregation','CanUploadFiles','bit',NULL,0),
('mySobek_User_Group_Edit_Aggregation','CanChangeVisibility','bit',NULL,0),
('mySobek_User_Group_Edit_Aggregation','CanDelete','bit',NULL,0),
('mySobek_User_Group_Editable_Link','UserGroupID','int',NULL,0),
('mySobek_User_Group_Editable_Link','EditableID','int',NULL,0),
('mySobek_User_Group_Editable_Link','CanEditMetadata','bit',NULL,0),
('mySobek_User_Group_Editable_Link','CanEditBehaviors','bit',NULL,0),
('mySobek_User_Group_Editable_Link','CanPerformQc','bit',NULL,0),
('mySobek_User_Group_Editable_Link','CanUploadFiles','bit',NULL,0),
('mySobek_User_Group_Editable_Link','CanChangeVisibility','bit',NULL,0),
('mySobek_User_Group_Editable_Link','CanDelete','bit',NULL,0),
('mySobek_User_Group_Item_Permissions','UserGroupPermissionID','int',NULL,0),
('mySobek_User_Group_Item_Permissions','UserGroupID','int',NULL,0),
('mySobek_User_Group_Item_Permissions','ItemID','int',NULL,1),
('mySobek_User_Group_Item_Permissions','isOwner','bit',NULL,0),
('mySobek_User_Group_Item_Permissions','canView','bit',NULL,1),
('mySobek_User_Group_Item_Permissions','canEditMetadata','bit',NULL,1),
('mySobek_User_Group_Item_Permissions','canEditBehaviors','bit',NULL,1),
('mySobek_User_Group_Item_Permissions','canPerformQc','bit',NULL,1),
('mySobek_User_Group_Item_Permissions','canUploadFiles','bit',NULL,1),
('mySobek_User_Group_Item_Permissions','canChangeVisibility','bit',NULL,1),
('mySobek_User_Group_Item_Permissions','canDelete','bit',NULL,1),
('mySobek_User_Group_Item_Permissions','customPermissions','varchar',-1,1),
('mySobek_User_Group_Item_Permissions','isDefaultPermissions','bit',NULL,0),
('mySobek_User_Group_Link','UserID','int',NULL,0),
('mySobek_User_Group_Link','UserGroupID','int',NULL,0),
('mySobek_User_Group_Link','IsGroupAdmin','bit',NULL,0),
('mySobek_User_Group_Template_Link','UserGroupID','int',NULL,0),
('mySobek_User_Group_Template_Link','TemplateID','int',NULL,0),
('mySobek_User_Item','UserItemID','int',NULL,0),
('mySobek_User_Item','UserFolderID','int',NULL,0),
('mySobek_User_Item','ItemOrder','int',NULL,0),
('mySobek_User_Item','UserNotes','nvarchar',2000,1),
('mySobek_User_Item','DateAdded','datetime',NULL,0),
('mySobek_User_Item','ItemID','int',NULL,0),
('mySobek_User_Item_Link','UserID','int',NULL,0),
('mySobek_User_Item_Link','ItemID','int',NULL,0),
('mySobek_User_Item_Link','RelationshipID','int',NULL,0),
('mySobek_User_Item_Link_Relationship','RelationshipID','int',NULL,0),
('mySobek_User_Item_Link_Relationship','RelationshipLabel','nvarchar',50,0),
('mySobek_User_Item_Link_Relationship','Include_In_Results','bit',NULL,0),
('mySobek_User_Item_Permissions','UserPermissionID','int',NULL,0),
('mySobek_User_Item_Permissions','UserID','int',NULL,0),
('mySobek_User_Item_Permissions','ItemID','int',NULL,0),
('mySobek_User_Item_Permissions','isOwner','bit',NULL,0),
('mySobek_User_Item_Permissions','canView','bit',NULL,1),
('mySobek_User_Item_Permissions','canEditMetadata','bit',NULL,1),
('mySobek_User_Item_Permissions','canEditBehaviors','bit',NULL,1),
('mySobek_User_Item_Permissions','canPerformQc','bit',NULL,1),
('mySobek_User_Item_Permissions','canUploadFiles','bit',NULL,1),
('mySobek_User_Item_Permissions','canChangeVisibility','bit',NULL,1),
('mySobek_User_Item_Permissions','canDelete','bit',NULL,1),
('mySobek_User_Item_Permissions','customPermissions','varchar',-1,1),
('mySobek_User_Request','UserRequestID','int',NULL,0),
('mySobek_User_Request','UserID','int',NULL,0),
('mySobek_User_Request','UserGroupID','int',NULL,1),
('mySobek_User_Request','RequestDate','datetime',NULL,0),
('mySobek_User_Request','RequestSubmitPermissions','bit',NULL,0),
('mySobek_User_Request','RequestUrl','nvarchar',255,1),
('mySobek_User_Request','Pending','bit',NULL,0),
('mySobek_User_Request','Approved','bit',NULL,0),
('mySobek_User_Request','Notes','nvarchar',2000,1),
('mySobek_User_Request','ApproverUserID','int',NULL,1),
('mySobek_User_Request','Code','nvarchar',255,1),
('mySobek_User_Search','UserSearchID','int',NULL,0),
('mySobek_User_Search','UserID','int',NULL,0),
('mySobek_User_Search','SearchURL','nvarchar',500,0),
('mySobek_User_Search','SearchDescription','nvarchar',500,0),
('mySobek_User_Search','ItemOrder','int',NULL,0),
('mySobek_User_Search','UserNotes','nvarchar',2000,0),
('mySobek_User_Search','DateAdded','datetime',NULL,0),
('mySobek_User_Settings','UserSettingID','bigint',NULL,0),
('mySobek_User_Settings','UserID','int',NULL,0),
('mySobek_User_Settings','Setting_Key','nvarchar',255,0),
('mySobek_User_Settings','Setting_Value','nvarchar',-1,0),
('mySobek_User_Template_Link','UserID','int',NULL,0),
('mySobek_User_Template_Link','TemplateID','int',NULL,0),
('mySobek_User_Template_Link','DefaultTemplate','bit',NULL,0);

-------------------------------------------------------------------------------
-- Missing tables: expected table doesn't exist at all
-------------------------------------------------------------------------------
DECLARE @TableName sysname, @ColumnName sysname;

DECLARE missing_tables_cur CURSOR LOCAL FAST_FORWARD FOR
	SELECT DISTINCT TableName
	FROM #ExpectedSchema es
	WHERE NOT EXISTS (SELECT 1 FROM sys.tables t WHERE t.name = es.TableName)
	ORDER BY TableName;

OPEN missing_tables_cur;
FETCH NEXT FROM missing_tables_cur INTO @TableName;
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT 'MISSING TABLE: ' + @TableName;
	FETCH NEXT FROM missing_tables_cur INTO @TableName;
END;
CLOSE missing_tables_cur;
DEALLOCATE missing_tables_cur;

-------------------------------------------------------------------------------
-- Missing columns: table exists, expected column doesn't
-------------------------------------------------------------------------------
DECLARE missing_cols_cur CURSOR LOCAL FAST_FORWARD FOR
	SELECT es.TableName, es.ColumnName
	FROM #ExpectedSchema es
	WHERE EXISTS (SELECT 1 FROM sys.tables t WHERE t.name = es.TableName)
	  AND NOT EXISTS (
		  SELECT 1
		  FROM sys.columns c
		  JOIN sys.tables t ON c.object_id = t.object_id
		  WHERE t.name = es.TableName AND c.name = es.ColumnName
	  )
	ORDER BY es.TableName, es.ColumnName;

OPEN missing_cols_cur;
FETCH NEXT FROM missing_cols_cur INTO @TableName, @ColumnName;
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT 'MISSING COLUMN: ' + @TableName + '.' + @ColumnName;
	FETCH NEXT FROM missing_cols_cur INTO @TableName, @ColumnName;
END;
CLOSE missing_cols_cur;
DEALLOCATE missing_cols_cur;

-------------------------------------------------------------------------------
-- Extra columns: DB has a column, on an expected table, that isn't in ver5_tables.sql
-------------------------------------------------------------------------------
DECLARE extra_cols_cur CURSOR LOCAL FAST_FORWARD FOR
	SELECT t.name, c.name
	FROM sys.tables t
	JOIN sys.columns c ON c.object_id = t.object_id
	WHERE t.name IN (SELECT DISTINCT TableName FROM #ExpectedSchema)
	  AND NOT EXISTS (
		  SELECT 1 FROM #ExpectedSchema es
		  WHERE es.TableName = t.name AND es.ColumnName = c.name
	  )
	ORDER BY t.name, c.name;

OPEN extra_cols_cur;
FETCH NEXT FROM extra_cols_cur INTO @TableName, @ColumnName;
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT 'EXTRA COLUMN (not in ver5_tables.sql): ' + @TableName + '.' + @ColumnName;
	FETCH NEXT FROM extra_cols_cur INTO @TableName, @ColumnName;
END;
CLOSE extra_cols_cur;
DEALLOCATE extra_cols_cur;

-------------------------------------------------------------------------------
-- Mismatched columns: both sides have it, but type / length / nullability differ
-------------------------------------------------------------------------------
DECLARE @ExpType varchar(50), @ActType varchar(50), @ExpLen int, @ActLen int, @ExpNull bit, @ActNull bit;

DECLARE mismatch_cur CURSOR LOCAL FAST_FORWARD FOR
	SELECT
		es.TableName,
		es.ColumnName,
		es.DataType,
		ty.name,
		es.MaxLen,
		CASE WHEN c.max_length = -1 THEN -1
			 WHEN ty.name IN ('nvarchar','nchar') THEN c.max_length / 2
			 ELSE c.max_length END,
		es.IsNullable,
		c.is_nullable
	FROM #ExpectedSchema es
	JOIN sys.tables t ON t.name = es.TableName
	JOIN sys.columns c ON c.object_id = t.object_id AND c.name = es.ColumnName
	JOIN sys.types ty ON ty.user_type_id = c.user_type_id
	ORDER BY es.TableName, es.ColumnName;

OPEN mismatch_cur;
FETCH NEXT FROM mismatch_cur INTO @TableName, @ColumnName, @ExpType, @ActType, @ExpLen, @ActLen, @ExpNull, @ActNull;
WHILE @@FETCH_STATUS = 0
BEGIN
	IF @ExpType <> @ActType
		PRINT 'TYPE MISMATCH: ' + @TableName + '.' + @ColumnName + ' - expected [' + @ExpType + '] but found [' + @ActType + ']';

	IF @ExpLen IS NOT NULL AND (@ActLen IS NULL OR @ExpLen <> @ActLen)
		PRINT 'LENGTH MISMATCH: ' + @TableName + '.' + @ColumnName + ' - expected length '
			+ CASE WHEN @ExpLen = -1 THEN 'max' ELSE CAST(@ExpLen AS varchar(10)) END
			+ ' but found ' + CASE WHEN @ActLen = -1 THEN 'max' ELSE CAST(ISNULL(@ActLen,-2) AS varchar(10)) END;

	IF @ExpNull <> @ActNull
		PRINT 'NULLABILITY MISMATCH: ' + @TableName + '.' + @ColumnName + ' - expected '
			+ CASE WHEN @ExpNull = 1 THEN 'NULL' ELSE 'NOT NULL' END
			+ ' but found ' + CASE WHEN @ActNull = 1 THEN 'NULL' ELSE 'NOT NULL' END;

	FETCH NEXT FROM mismatch_cur INTO @TableName, @ColumnName, @ExpType, @ActType, @ExpLen, @ActLen, @ExpNull, @ActNull;
END;
CLOSE mismatch_cur;
DEALLOCATE mismatch_cur;

DROP TABLE #ExpectedSchema;

PRINT 'Schema comparison complete.';
GO
