import { expect, type APIRequestContext } from '@playwright/test';
import { Given, When, Then } from './fixtures';
import type { World } from './fixtures';

// Raw HTTP requests, without the browser: redirects are NOT followed, so a scenario can assert
// exactly what the server sent back (status, Location header, body).

const ROBOT_USER_AGENT = 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)';

// The comment line SobekCM puts at the top of the robots.txt it generates while Robots:BlockAll is on
// (BlockAllRobotsInitializer.Generated_Robots_Txt) -- present means the generated one, absent means the
// site's real robots.txt file
const GENERATED_ROBOTS_TXT_MARKER = 'Generated by SobekCM because Robots:BlockAll is on';

// ----- Which site -----
// Robots:BlockAll (appsettings.json) is read once when the site starts, so a scenario can't flip it.
// Instead, a run can point at two sites: BASE_URL, plus a second address with the other setting.
// The e2e environment serves one deployment twice -- port 80 blocks all robots, like the real demo and
// testing sites, and port 8080 allows them (ROBOTS_ALLOWED_BASE_URL). Without the second address, a
// scenario runs against BASE_URL when that site happens to match, and otherwise skips.

// A site with Robots:BlockAll on tags every page response with X-Robots-Tag: noindex
// (BlockAllRobotsInitializer), which is the only outside sign of the setting
async function blocksAllRobots(request: APIRequestContext, siteBaseUrl: string | undefined): Promise<boolean> {
  const home = await request.get(siteBaseUrl ? new URL('/', siteBaseUrl).toString() : '/', { maxRedirects: 0 });
  return (home.headers()['x-robots-tag'] ?? '').includes('noindex');
}

async function chooseSite(request: APIRequestContext, world: World, skip: (condition: boolean, reason: string) => void,
                          blocking: boolean, envVariable: string) {
  const configured = process.env[envVariable];
  if (configured) {
    // A configured address that doesn't behave as named is a broken environment, not something to skip
    expect(await blocksAllRobots(request, configured), `${envVariable} (${configured}) should ${blocking ? '' : 'not '}block all robots`).toBe(blocking);
    world.siteBaseUrl = configured;
    return;
  }
  skip(await blocksAllRobots(request, undefined) !== blocking,
    `This site ${blocking ? 'allows' : 'blocks all'} robots, and ${envVariable} isn't set`);
}

Given('a site that blocks all robots', async ({ request, world, $test }) => {
  await chooseSite(request, world, (c, r) => $test.skip(c, r), true, 'BLOCKALL_BASE_URL');
});

Given('a site that allows robots', async ({ request, world, $test }) => {
  await chooseSite(request, world, (c, r) => $test.skip(c, r), false, 'ROBOTS_ALLOWED_BASE_URL');
});

function address(world: World, path: string): string {
  return world.siteBaseUrl ? new URL(path, world.siteBaseUrl).toString() : path;
}

// ----- Requests -----

When('I request {string}', async ({ request, world }, path: string) => {
  world.apiUrl = path;
  world.apiResponse = await request.get(address(world, path), { maxRedirects: 0 });
  world.apiBody = await world.apiResponse.text();
});

When('a search engine robot requests {string}', async ({ request, world }, path: string) => {
  world.apiUrl = path;
  world.apiResponse = await request.get(address(world, path), { maxRedirects: 0, headers: { 'User-Agent': ROBOT_USER_AGENT } });
  world.apiBody = await world.apiResponse.text();
});

// ----- Responses -----

Then('the HTTP status should be {int}', async ({ world }, status: number) => {
  expect(world.apiResponse!.status()).toBe(status);
});

Then('the HTTP status should not be {int}', async ({ world }, status: number) => {
  expect(world.apiResponse!.status()).not.toBe(status);
});

Then('the response should redirect to {string}', async ({ world, baseURL }, expected: string) => {
  const status = world.apiResponse!.status();
  expect([301, 302, 303, 307, 308]).toContain(status);
  const location = new URL(world.apiResponse!.headers()['location'], world.siteBaseUrl ?? baseURL);
  expect(decodeURIComponent(location.pathname + location.search)).toBe(expected);
});

Then('the response should not redirect back to the same address', async ({ world, baseURL }) => {
  const location = world.apiResponse!.headers()['location'];
  if (!location) return;
  const site = world.siteBaseUrl ?? baseURL;
  const requested = new URL(world.apiUrl!, site);
  const target = new URL(location, site);
  expect(target.pathname + target.search, 'server redirected the request to itself').not.toBe(requested.pathname + requested.search);
});

Then('the response body should contain {string}', async ({ world }, text: string) => {
  expect(world.apiBody).toContain(text);
});

Then('the response body should not contain {string}', async ({ world }, text: string) => {
  expect(world.apiBody).not.toContain(text);
});

Then('the response should be an HTML page', async ({ world }) => {
  expect(world.apiResponse!.headers()['content-type']).toContain('text/html');
  expect(world.apiBody).toMatch(/<html/i);
});

Then('the robots.txt should be the one SobekCM generates', async ({ world }) => {
  expect(world.apiBody).toContain(GENERATED_ROBOTS_TXT_MARKER);
});

Then("the robots.txt should be the site's own file", async ({ world }) => {
  expect(world.apiBody, 'got the generated robots.txt instead of the file on disk').not.toContain(GENERATED_ROBOTS_TXT_MARKER);
});
