<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>SobekCM_Builder_Service</AssemblyName>
    <RootNamespace>SobekCM_Builder_Service</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <!-- Worker service host + Windows Service integration -->
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SobekCM_Builder_Library\SobekCM_Builder_Library.csproj" />
    <ProjectReference Include="..\SobekCM_Core\SobekCM_Core.csproj" />
    <ProjectReference Include="..\SobekCM_Engine_Library\SobekCM_Engine_Library.csproj" />
    <ProjectReference Include="..\SobekCM_Resource_Object\SobekCM_Resource_Object.csproj" />
    <ProjectReference Include="..\SobekCM_Tools\SobekCM_Tools.csproj" />
  </ItemGroup>

</Project>
