#region Using directives

using Microsoft.AspNetCore.Http;
using SobekCM.Core.Aggregations;
using SobekCM.Core.ApplicationState;
using SobekCM.Core.Client;
using SobekCM.Core.Configuration.Localization;
using SobekCM.Core.MemoryMgmt;
using SobekCM.Core.Navigation;
using SobekCM.Engine_Library.Configuration;
using SobekCM.Engine_Library.Database;
using SobekCM.Library.HTML.Helpers;
using SobekCM.Library.Localization;
using SobekCM.Library.UI;
using SobekCM.Tools;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.IO;
using System.Linq;

#endregion

namespace SobekCM.Library.HTML
{
    /// <summary> Internal html subwriter renders all of the screens about the collections and items
    /// held within this digital library, the list of items edited or recently added, and the current memory profile </summary>
    /// <remarks> This class extends the <see cref="abstractHtmlSubwriter"/> abstract class. </remarks>
    public class Internal_HtmlSubwriter : abstractHtmlSubwriter
    {

        /// <summary> Constructor for a new instance of the Internal_HtmlSubwriter class </summary>
        /// <param name="RequestSpecificValues"> All the necessary, non-global data specific to the current request </param>
        public Internal_HtmlSubwriter(RequestCache RequestSpecificValues) : base(RequestSpecificValues)
        {
            // Do nothing
        }

        /// <summary> Writes the HTML generated by this internal html subwriter directly to the response stream </summary>
        /// <param name="Output"> Stream to which to write the HTML for this subwriter </param>
        /// <param name="Tracer"> Trace object keeps a list of each method executed and important milestones in rendering </param>
        /// <returns> TRUE -- Value indicating if html writer should finish the page immediately after this, or if there are other controls or routines which need to be called first </returns>
        public override bool Write_HTML(TextWriter Output, Custom_Tracer Tracer)
        {
            Tracer.Add_Trace("Internal_HtmlSubwriter.Write_HTML", "Rendering HTML");

            string language = RequestSpecificValues.Current_Mode.Language;

            string collection_details_title = Localization_Gateway.Internal.Collection_Details_Title(language);
            string new_items_title = Localization_Gateway.Internal.New_Items_Title(language);
            string memory_mgmt_title = Localization_Gateway.Internal.Memory_Mgmt_Title(language);
            string WORDMARKS_TITLE = Localization_Gateway.Internal.Wordmarks_Title(language);
            string BUILD_FAILURES_TITLE = Localization_Gateway.Internal.Build_Failures_Title(language);
            string UNAUTHORIZED_TITLE = Localization_Gateway.Internal.Unauthorized_Title(language);

            // Ensure there is a valid RequestSpecificValues.Current_User, and the RequestSpecificValues.Current_User is internal
            bool isAuthorized = (RequestSpecificValues.Current_User != null) && ((RequestSpecificValues.Current_User.Is_Internal_User) || (RequestSpecificValues.Current_User.Is_Portal_Admin) || (RequestSpecificValues.Current_User.Is_System_Admin));

            // Save the current type
            Internal_Type_Enum type = RequestSpecificValues.Current_Mode.Internal_Type;

            // Add the banner
            Banner_HtmlHelper.Add_Banner(Output, "sbkAhs_BannerDiv", WebPage_Title.Replace("{0} ", ""), RequestSpecificValues.Current_Mode, RequestSpecificValues.HTML_Skin, RequestSpecificValues.Top_Collection);

            if (!isAuthorized)
            {
                Output.WriteLine("  <h1>" + UNAUTHORIZED_TITLE + "</h1>");

                Output.WriteLine("<div class=\"SobekText\">");
                Output.WriteLine("<br /><br />");
                Output.WriteLine("<blockquote>");
                Output.WriteLine(Localization_Gateway.Internal.Unauthorized_Message(language));
                Output.WriteLine("<br /><br />");
                Output.WriteLine("<a href=\"" + RequestSpecificValues.Current_Mode.Base_URL + "l\"> " + Localization_Gateway.Internal.Return_Home_Link(language) + " </a>");
                Output.WriteLine("</blockquote>");
                Output.WriteLine("<br /><br />");
                Output.WriteLine("</div>");

            }
            else
            {
                // Add the RequestSpecificValues.Current_User-specific main menu
                MainMenus_HtmlHelper.Add_UserSpecific_Main_Menu(Output, RequestSpecificValues);

                // Start the page container
                Output.WriteLine("<div id=\"pagecontainer\">");
                Output.WriteLine("<br />");

                // Determine the title
                string stat_title = String.Empty;
                switch (type)
                {
                    case Internal_Type_Enum.Aggregations_List:
                    case Internal_Type_Enum.Aggregations_Tree:
                        stat_title = collection_details_title;
                        break;

                    case Internal_Type_Enum.New_Items:
                        stat_title = new_items_title;
                        break;

                    case Internal_Type_Enum.Build_Failures:
                        stat_title = BUILD_FAILURES_TITLE;
                        break;

                    case Internal_Type_Enum.Cache:
                        stat_title = memory_mgmt_title;
                        break;

                    case Internal_Type_Enum.Wordmarks:
                        stat_title = WORDMARKS_TITLE;
                        break;
                }

                Output.WriteLine("  <h1 style=\"margin-bottom:0px\">" + stat_title + "</h1>");

                // Set the type back
                RequestSpecificValues.Current_Mode.Internal_Type = type;

                // Add the appropriate text
                switch (type)
                {
                    case Internal_Type_Enum.Aggregations_List:
                        add_aggregations_master_list_html(Output, Tracer);
                        break;

                    case Internal_Type_Enum.Aggregations_Tree:
                        add_aggregations_tree_html(Output, Tracer);
                        break;

                    case Internal_Type_Enum.Cache:
                        add_cache_html(Output, Tracer);
                        break;


                    case Internal_Type_Enum.New_Items:
                        DataTable newItems = Engine_Database.Tracking_Update_List(Tracer);
                        add_new_item_html(Output, newItems, Tracer);
                        break;

                    case Internal_Type_Enum.Build_Failures:
                        int start_month = DateTime.Now.Month;
                        int start_year = DateTime.Now.Year;
                        int end_month = DateTime.Now.Month;
                        int end_year = DateTime.Now.Year;
                        if ((!String.IsNullOrEmpty(RequestSpecificValues.Current_Mode.Info_Browse_Mode)) && (RequestSpecificValues.Current_Mode.Info_Browse_Mode.Length == 12))
                        {
                            Int32.TryParse(RequestSpecificValues.Current_Mode.Info_Browse_Mode.Substring(0, 4), out start_year);
                            Int32.TryParse(RequestSpecificValues.Current_Mode.Info_Browse_Mode.Substring(4, 2), out start_month);
                            Int32.TryParse(RequestSpecificValues.Current_Mode.Info_Browse_Mode.Substring(6, 4), out end_year);
                            Int32.TryParse(RequestSpecificValues.Current_Mode.Info_Browse_Mode.Substring(10, 2), out end_month);

                            if (start_year > end_year)
                            {
                                int save_year = start_year;
                                int save_month = start_month;
                                start_year = end_year;
                                start_month = end_month;
                                end_year = save_year;
                                end_month = save_month;
                            }

                            if ((start_year == end_year) && (end_month < start_month))
                            {
                                int save_month2 = start_month;
                                start_month = end_month;
                                end_month = save_month2;
                            }
                        }
                        add_build_failures(Output, start_month, start_year, end_month, end_year, Tracer);
                        break;

                    case Internal_Type_Enum.Wordmarks:
                        add_wordmarks(Output, Tracer);
                        break;
                }
            }

            // ===== Begin original Write_Final_HTML =====
            Output.WriteLine("<!-- Close the pagecontainer div -->");
            Output.WriteLine("</div>");
            Output.WriteLine();
            // ===== End original Write_Final_HTML =====

            return true;
        }

        #region Method to add the wordmarks to the response stream

        /// <summary> Adds the wordmarks to the response stream</summary>
        /// <param name="Output"> Stream to which to write the HTML for this subwriter </param>
        /// <param name="Tracer"> Trace object keeps a list of each method executed and important milestones in rendering </param>
        protected internal void add_wordmarks(TextWriter Output, Custom_Tracer Tracer)
        {
            Tracer.Add_Trace("Internal_HtmlSubwriter.add_wordmarks", "Rendering HTML");

            if (UI_ApplicationCache_Gateway.Icon_List.Count > 0)
            {
                Output.WriteLine("<br />");
                Output.WriteLine("");

                if ((RequestSpecificValues.Current_User != null) && ((RequestSpecificValues.Current_User.Is_Portal_Admin) || (RequestSpecificValues.Current_User.Is_System_Admin)))
                {
                    RequestSpecificValues.Current_Mode.Mode = Display_Mode_Enum.Administrative;
                    RequestSpecificValues.Current_Mode.Admin_Type = Admin_View_Codes.Wordmarks;

                    Output.Write(String.Format(Localization_Gateway.Internal.Wordmarks_Admin_Manage_Html(RequestSpecificValues.Current_Mode.Language), UrlWriterHelper.Redirect_URL(RequestSpecificValues.Current_Mode)) + "<br />");

                    RequestSpecificValues.Current_Mode.Mode = Display_Mode_Enum.Internal;
                }

                Output.WriteLine("</div>");
                Output.WriteLine("<center>");
                Output.WriteLine("<table border=\"0px\" cellspacing=\"0px\" width=\"1000px\" class=\"statsTable\">");
                Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"5\"></td></tr>");
                Output.WriteLine("  <tr align=\"center\" valign=\"bottom\" >");

                int current_column = 0;
                var sortedIcons = new SortedList<string, Wordmark_Icon>();
                foreach (Wordmark_Icon thisIcon in UI_ApplicationCache_Gateway.Icon_List.Values)
                {
                    sortedIcons.Add(thisIcon.Code, thisIcon);
                }

                foreach (Wordmark_Icon thisIcon in sortedIcons.Values)
                {
                    Output.Write("    <td width=\"200px\">");
                    if (thisIcon.Link.Length > 0)
                        Output.Write("<a href=\"" + thisIcon.Link + "\" target=\"_blank\">");
                    Output.Write("<img border=\"0px\" class=\"SobekcmItemWorkdmark\" src=\"" + RequestSpecificValues.Current_Mode.Base_URL + "design/wordmarks/" + thisIcon.Image_FileName + "\"");
                    if (thisIcon.Title.Length > 0)
                        Output.Write(" title=\"" + thisIcon.Title + "\"");
                    Output.Write(" />");
                    if (thisIcon.Link.Length > 0)
                        Output.Write("</a>");
                    Output.WriteLine("<br /><b>" + thisIcon.Code + "</b></td>");

                    current_column++;

                    if (current_column >= 5)
                    {
                        Output.WriteLine("  </tr>");
                        Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"5\"></td></tr>");
                        Output.WriteLine("  <tr align=\"center\" valign=\"bottom\" >");
                        current_column = 0;
                    }
                }

                Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"5\"></td></tr>");

                Output.WriteLine("</table>");
                Output.WriteLine("</center>");
                Output.WriteLine("<br /><br />");
                Output.WriteLine("<div id=\"pagecontainer_resumed\">");
            }
            else
            {
                Output.WriteLine("<br /><br />");
                Output.WriteLine("<div style=\"text-align:center;width:100%;\">" + Localization_Gateway.Internal.No_Wordmarks_Message(RequestSpecificValues.Current_Mode.Language) + "</div>");

                Output.WriteLine("<br /><br />");

                if ((RequestSpecificValues.Current_User != null) && ((RequestSpecificValues.Current_User.Is_Portal_Admin) || (RequestSpecificValues.Current_User.Is_System_Admin)))
                {
                    RequestSpecificValues.Current_Mode.Mode = Display_Mode_Enum.Administrative;
                    RequestSpecificValues.Current_Mode.Admin_Type = Admin_View_Codes.Wordmarks;

                    Output.Write(String.Format(Localization_Gateway.Internal.Wordmarks_Admin_Manage_Html(RequestSpecificValues.Current_Mode.Language), UrlWriterHelper.Redirect_URL(RequestSpecificValues.Current_Mode)) + "<br />");

                    RequestSpecificValues.Current_Mode.Mode = Display_Mode_Enum.Internal;
                }
                else
                {

                    Output.WriteLine("<div style=\"text-align:center;width:100%;\">" + Localization_Gateway.Internal.Wordmarks_Admin_Add_Message(RequestSpecificValues.Current_Mode.Language) + "</div>");
                }

                Output.WriteLine("<br /><br />");
            }
        }

        #endregion

        #region Method to add the build failures to the response stream

        /// <summary> Adds the list of build failures to the output stream for a given date range</summary>
        /// <param name="FirstMonth"> Month for the first date in the date range </param>
        /// <param name="FirstYear"> Year for the first date in the date range </param>
        /// <param name="SecondYear"> Year for the last date in the date range</param>
        /// <param name="SecondMonth"> Month for the last date in the date range</param>
        /// <param name="Output"> Stream to which to write the HTML for this subwriter </param>
        /// <param name="Tracer"> Trace object keeps a list of each method executed and important milestones in rendering </param>
        protected internal void add_build_failures(TextWriter Output, int FirstMonth, int FirstYear, int SecondMonth, int SecondYear, Custom_Tracer Tracer)
        {
            RequestSpecificValues.Current_Mode.Internal_Type = Internal_Type_Enum.Build_Failures;

            Tracer.Add_Trace("Internal_HtmlSubwriter.add_build_failures", "Rendering HTML");

            string language = RequestSpecificValues.Current_Mode.Language;

            string currentInfoBrowseMode = RequestSpecificValues.Current_Mode.Info_Browse_Mode;
            RequestSpecificValues.Current_Mode.Info_Browse_Mode = String.Empty;
            string redirect_url = UrlWriterHelper.Redirect_URL(RequestSpecificValues.Current_Mode);
            RequestSpecificValues.Current_Mode.Info_Browse_Mode = currentInfoBrowseMode;

            Output.WriteLine("<br />");
            Output.WriteLine("");

            Output.WriteLine("<div class=\"SobekText\">");
            Output.WriteLine("<p>" + Localization_Gateway.Internal.Build_Failures_Intro(language) + "</p>");
            Output.WriteLine();
            Output.WriteLine("<h2>" + Localization_Gateway.Internal.Selected_Date_Range(language) + "</h2>");
            Output.WriteLine();
            Output.WriteLine("<p>" + Localization_Gateway.Internal.Build_Failures_Search_Prompt(language) + "</p>");

            Output.WriteLine("<form name=\"statistics_form\" action=\"Javascript:date_jump_sobekcm('" + redirect_url + "')\" id=\"addedForm\">");
            Output.WriteLine("  <blockquote>");
            Output.WriteLine("    " + Localization_Gateway.Internal.From_Label(language) + " <select name=\"date1_selector\" class=\"SobekStatsDateSelector\">");

            int select_month = DateTime.Now.Month;
            int select_year = DateTime.Now.Year - 1;
            while ((select_month != DateTime.Now.Month) || (select_year != DateTime.Now.Year))
            {
                if ((FirstMonth == select_month) && (FirstYear == select_year))
                {
                    Output.WriteLine("      <option value=\"" + select_year + select_month.ToString().PadLeft(2, '0') + "\" selected=\"selected\" >" + Localization_Gateway.Internal.Month(select_month, language) + " " + select_year + "</option>");
                }
                else
                {
                    Output.WriteLine("      <option value=\"" + select_year + select_month.ToString().PadLeft(2, '0') + "\">" + Localization_Gateway.Internal.Month(select_month, language) + " " + select_year + "</option>");
                }

                select_month++;
                if (select_month > 12)
                {
                    select_month = 1;
                    select_year++;
                }
            }
            if ((FirstMonth == select_month) && (FirstYear == select_year))
            {
                Output.WriteLine("      <option value=\"" + select_year + select_month.ToString().PadLeft(2, '0') + "\" selected=\"selected\" >" + Localization_Gateway.Internal.Month(select_month, language) + " " + select_year + "</option>");
            }
            else
            {
                Output.WriteLine("      <option value=\"" + select_year + select_month.ToString().PadLeft(2, '0') + "\">" + Localization_Gateway.Internal.Month(select_month, language) + " " + select_year + "</option>");
            }
            Output.WriteLine("    </select>");
            Output.WriteLine("    &nbsp; &nbsp;");
            Output.WriteLine("    " + Localization_Gateway.Internal.To_Label(language) + " <select name=\"date2_selector\" class=\"SobekStatsDateSelector\" >");

            select_month = DateTime.Now.Month;
            select_year = DateTime.Now.Year - 1;
            while ((select_month != DateTime.Now.Month) || (select_year != DateTime.Now.Year))
            {
                if ((SecondMonth == select_month) && (SecondYear == select_year))
                {
                    Output.WriteLine("      <option value=\"" + select_year + select_month.ToString().PadLeft(2, '0') + "\" selected=\"selected\" >" + Localization_Gateway.Internal.Month(select_month, language) + " " + select_year + "</option>");
                }
                else
                {
                    Output.WriteLine("      <option value=\"" + select_year + select_month.ToString().PadLeft(2, '0') + "\">" + Localization_Gateway.Internal.Month(select_month, language) + " " + select_year + "</option>");
                }

                select_month++;
                if (select_month > 12)
                {
                    select_month = 1;
                    select_year++;
                }
            }
            if ((SecondMonth == select_month) && (SecondYear == select_year))
            {
                Output.WriteLine("      <option value=\"" + select_year + select_month.ToString().PadLeft(2, '0') + "\" selected=\"selected\" >" + Localization_Gateway.Internal.Month(select_month, language) + " " + select_year + "</option>");
            }
            else
            {
                Output.WriteLine("      <option value=\"" + select_year + select_month.ToString().PadLeft(2, '0') + "\">" + Localization_Gateway.Internal.Month(select_month, language) + " " + select_year + "</option>");
            }

            Output.WriteLine("    </select>");
            Output.WriteLine("    &nbsp; &nbsp;");
            Output.WriteLine("    <button title=\"" + Localization_Gateway.Internal.Select_Range_Title(language) + "\" class=\"go_button\" onclick=\"date_jump_sobekcm('" + redirect_url + "'); return false;\"></button>");
            Output.WriteLine("  </blockquote>");
            Output.WriteLine("</form>");
            Output.WriteLine("<p>" + Localization_Gateway.Internal.Change_Date_Instructions(language) + "</p>");
            Output.WriteLine();
            Output.WriteLine("<h2>" + Localization_Gateway.Internal.Build_Failures_Warnings_Header(language) + "</h2>");
            Output.WriteLine();
            Output.WriteLine("</div>");

            // Pull this date from the database
            DataTable values = Engine_Database.Builder_Get_Error_Logs(Tracer, new DateTime(FirstYear, FirstMonth, 1), new DateTime(SecondYear, SecondMonth, 1).AddMonths(1));

            if ((values == null) || (values.Rows.Count == 0))
            {
                Output.WriteLine("<br />");
                Output.WriteLine("<center><b>" + Localization_Gateway.Internal.No_Failures_Message(language) + "</b></center>");
                Output.WriteLine("<br /><br />");
                return;
            }


            // Add the header information
            Output.WriteLine("<center>");
            Output.WriteLine("<table width=\"700px\" border=\"0px\" cellspacing=\"0px\"  class=\"statsTable\">");
            Output.WriteLine("  <tr align=\"left\" bgcolor=\"#0022a7\" >");
            Output.WriteLine("    <th width=\"150px\"><span style=\"color: White\"><b>" + Localization_Gateway.Internal.Bibid_Vid_Header(language) + "</b></span></th>");
            Output.WriteLine("    <th width=\"150px\"><span style=\"color: White\"><b>" + Localization_Gateway.Internal.Mets_Type_Header(language) + "</b></span></th>");
            Output.WriteLine("    <th width=\"400px\"><span style=\"color: White\"><b>" + Localization_Gateway.Internal.Description_Header(language) + "</b></span></th>");
            Output.WriteLine("  </tr>");

            // Now, add each line
            string lastDate = String.Empty;
            foreach (DataRow thisRow in values.Rows)
            {
                // Get this date
                string thisDate = thisRow[4].ToString().Split(" ".ToCharArray())[0];

                // Is this a new date?
                if (thisDate != lastDate)
                {
                    Output.WriteLine("  <tr align=\"left\" bgcolor=\"#7d90d5\" ><td colspan=\"3\"><span style=\"color: White\"><b>" + thisDate + "</b></span></td></tr>");
                    lastDate = thisDate;
                }

                Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"3\"></td></tr>");
                Output.WriteLine("  <tr align=\"left\">");
                Output.WriteLine("    <td><a href=\"?b=" + thisRow[0] + "&v=" + thisRow[1] + "\">" + thisRow[0] + " : " + thisRow[1] + "</a></td>");
                Output.WriteLine("    <td>" + thisRow[2] + "</td>");
                Output.WriteLine("    <td>" + thisRow[3] + "</td>");
                Output.WriteLine("  </tr>");
            }
            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"3\"></td></tr>");

            // Close out this table
            Output.WriteLine("</table>");
            Output.WriteLine("</center>");
            Output.WriteLine("<br />");
            Output.WriteLine();

        }

        #endregion

        #region Method to add the current memory profile to the response stream

        /// <summary> Adds the current memory profile to the response stream </summary>
        /// <param name="Output"> Stream to which to write the HTML for this subwriter </param>
        /// <param name="Tracer"> Trace object keeps a list of each method executed and important milestones in rendering </param>
        protected internal void add_cache_html(TextWriter Output, Custom_Tracer Tracer)
        {
            Tracer.Add_Trace("Internal_HtmlSubwriter.add_cache_html", "Rendering HTML");

            SobekCM_Application.ApplicationState applicationState = SobekCM_Application.State;
            ISession session = Context.Session;
            List<string> sessionKeys = session.Keys.ToList();

            string language = RequestSpecificValues.Current_Mode.Language;

            string global_values = Localization_Gateway.Internal.Global_Values_Header(language);
            string application_state = Localization_Gateway.Internal.Application_State_Header(language);
            string local_cache_state = Localization_Gateway.Internal.Local_Cache_State_Header(language);
            string session_state = Localization_Gateway.Internal.Session_State_Header(language);
            string variable_name = Localization_Gateway.Internal.Instance_Name_Header(language);
            string key = Localization_Gateway.Internal.Key_Header(language);
            string objectTitle = Localization_Gateway.Internal.Object_Header(language);

            // Start the application data
            Output.WriteLine("<br />");
            Output.WriteLine("");
            Output.WriteLine("<br /><br />");

            // Add the header information
            Output.WriteLine("<table width=\"720px\" cellspacing=\"0px\">");
            Output.WriteLine("  <tr align=\"center\" bgcolor=\"#0022a7\"><td colspan=\"2\"><span style=\"color: White\"><b>" + global_values + "</b></span></td></tr>");
            Output.WriteLine("  <tr align=\"left\" bgcolor=\"#7d90d5\">");
            Output.WriteLine("    <th align=\"left\"><span style=\"color: White\">" + variable_name + "</span></th>");
            Output.WriteLine("    <th align=\"left\"><span style=\"color: White\">" + objectTitle + "</span></th>");
            Output.WriteLine("  </tr>");

            // Add each global value
            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("  <tr align=\"left\">" + Environment.NewLine + "    <td>Checked_List</td>" + Environment.NewLine + "    <td>SobekCM.Library.Application_State.Checked_Out_Items_List</td>" + Environment.NewLine + "  </tr>");

            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("  <tr align=\"left\">" + Environment.NewLine + "    <td>Codes</td>" + Environment.NewLine + "    <td>SobekCM.Library.Application_State.Aggregation_Code_Manager</td>" + Environment.NewLine + "  </tr>");

            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("  <tr align=\"left\">" + Environment.NewLine + "    <td>Collection_Aliases</td>" + Environment.NewLine + "    <td>Dictionary&lt;string,string&gt;</td>" + Environment.NewLine + "  </tr>");

            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("  <tr align=\"left\">" + Environment.NewLine + "    <td>Icon_List</td>" + Environment.NewLine + "    <td>Dictionary&lt;string,SobekCM.Library.Application_State.Wordmark_Icon&gt;</td>" + Environment.NewLine + "  </tr>");

            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("  <tr align=\"left\">" + Environment.NewLine + "    <td>IP_Restrictions</td>" + Environment.NewLine + "    <td>SobekCM.Library.Application_State.IP_Restriction_Ranges</td>" + Environment.NewLine + "  </tr>");

            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("  <tr align=\"left\">" + Environment.NewLine + "    <td>Item_List</td>" + Environment.NewLine + "    <td>SobekCM.Library.Application_State.Item_Lookup_Object</td>" + Environment.NewLine + "  </tr>");

            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("  <tr align=\"left\">" + Environment.NewLine + "    <td>Last_Refresh</td>" + Environment.NewLine + "    <td>DateTime</td>" + Environment.NewLine + "  </tr>");

            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("  <tr align=\"left\">" + Environment.NewLine + "    <td>Search_History</td>" + Environment.NewLine + "    <td>SobekCM.Library.Application_State.Recent_Searches</td>" + Environment.NewLine + "  </tr>");

            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("  <tr align=\"left\">" + Environment.NewLine + "    <td>StopWords</td>" + Environment.NewLine + "    <td>List&lt;string&gt;</td>" + Environment.NewLine + "  </tr>");

            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("  <tr align=\"left\">" + Environment.NewLine + "    <td>Skins</td>" + Environment.NewLine + "    <td>SobekCM.Library.Skins.Web_Skin_Collection</td>" + Environment.NewLine + "  </tr>");

            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("  <tr align=\"left\">" + Environment.NewLine + "    <td>Stats_Date_Range</td>" + Environment.NewLine + "    <td>SobekCM.Library.Application_State.Statistics_Dates</td>" + Environment.NewLine + "  </tr>");

            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("  <tr align=\"left\">" + Environment.NewLine + "    <td>Thematic_Headings</td>" + Environment.NewLine + "    <td>List&lt;SobekCM.Library.Aggregations.Thematic_Heading&gt;</td>" + Environment.NewLine + "  </tr>");

            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("  <tr align=\"left\">" + Environment.NewLine + "    <td>Translation</td>" + Environment.NewLine + "    <td>SobekCM.Library.Application_State.Language_Support_Info</td>" + Environment.NewLine + "  </tr>");

            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("  <tr align=\"left\">" + Environment.NewLine + "    <td>URL_Portals</td>" + Environment.NewLine + "    <td>SobekCM.Library.Application_State.Portal_List</td>" + Environment.NewLine + "  </tr>");

            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("  <tr align=\"left\">" + Environment.NewLine + "    <td>Version</td>" + Environment.NewLine + "    <td>string</td>" + Environment.NewLine + "  </tr>");

            // Close out this table
            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("</table>");

            // Start the application data
            Output.WriteLine("<br /><br />");

            // Add the header information
            Output.WriteLine("<table width=\"720px\" cellspacing=\"0px\">");
            Output.WriteLine("  <tr align=\"center\" bgcolor=\"#0022a7\"><td colspan=\"2\"><span style=\"color: White\"><b>" + application_state + "</b></span></td></tr>");
            Output.WriteLine("  <tr align=\"left\" bgcolor=\"#7d90d5\">");
            Output.WriteLine("    <th align=\"left\"><span style=\"color: White\">" + key + "</span></th>");
            Output.WriteLine("    <th align=\"left\"><span style=\"color: White\">" + objectTitle + "</span></th>");
            Output.WriteLine("  </tr>");

            try
            {
                // Step through all the keys
                string[] allkeys = applicationState.AllKeys;
                if (allkeys.Length == 0)
                {
                    Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
                    Output.WriteLine("  <tr align=\"left\">");
                    Output.WriteLine("    <td><i>" + Localization_Gateway.Internal.None_Placeholder(language) + "</i></td>");
                    Output.WriteLine("    <td><i>" + Localization_Gateway.Internal.None_Placeholder(language) + "</td>");
                    Output.WriteLine("  </tr>");
                }
                else
                {
                    foreach (string thisKey in allkeys)
                    {
                        // Add this row
                        Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
                        Output.WriteLine("  <tr align=\"left\">");
                        Output.WriteLine("    <td>" + thisKey + "</td>");
                        if (applicationState[thisKey] != null)
                        {
                            Output.WriteLine("    <td>" + applicationState[thisKey].GetType().FullName + "</td>");
                        }
                        else
                        {
                            Output.WriteLine("    <td><i>NULL</i></td>");
                        }
                        Output.WriteLine("  </tr>");
                    }
                }
            }
            catch (Exception)
            {
                Output.WriteLine("<strong>" + Localization_Gateway.Internal.Application_State_Error(language) + "</strong>");
            }

            // Close out this table
            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("</table>");

            // Start the locally cached data
            Output.WriteLine("<br /><br />");

            // Add the header information
            Output.WriteLine("<table width=\"720px\" cellspacing=\"0px\">");
            Output.WriteLine("  <tr align=\"center\" bgcolor=\"#0022a7\"><td colspan=\"2\"><span style=\"color: White\"><b>" + local_cache_state + "</b></span></td></tr>");
            Output.WriteLine("  <tr align=\"left\" bgcolor=\"#7d90d5\">");
            Output.WriteLine("    <th align=\"left\"><span style=\"color: White\">" + key + "</span></th>");
            Output.WriteLine("    <th align=\"left\"><span style=\"color: White\">" + objectTitle + "</span></th>");
            Output.WriteLine("  </tr>");

            try
            {
                // Now, get the information from the cache
                ReadOnlyCollection<Cached_Object_Info> locally_cached_objects = CachedDataManager.Locally_Cached_Objects;
                if (locally_cached_objects.Count == 0)
                {
                    Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
                    Output.WriteLine("  <tr align=\"left\">");
                    Output.WriteLine("    <td><i>" + Localization_Gateway.Internal.None_Placeholder(language) + "</i></td>");
                    Output.WriteLine("    <td><i>" + Localization_Gateway.Internal.None_Placeholder(language) + "</td>");
                    Output.WriteLine("  </tr>");
                }
                else
                {
                    foreach (Cached_Object_Info thisItem in locally_cached_objects)
                    {
                        // Add this row
                        Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
                        Output.WriteLine("  <tr align=\"left\">");
                        Output.WriteLine("    <td>" + thisItem.Object_Key + "</td>");
                        string type = thisItem.Object_Type.FullName;
                        if (type == "System.Collections.Generic.List`1[[System.String, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]")
                            type = "generic List&lt;System.String&gt;";
                        Output.WriteLine("    <td>" + type + "</td>");
                        Output.WriteLine("  </tr>");
                    }
                }
            }
            catch (Exception)
            {
                Output.WriteLine("<strong>" + Localization_Gateway.Internal.Local_Cache_Error(language) + "</strong>");
            }

            // Close out this table
            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("</table>");

            // Start the session data
            Output.WriteLine("<br /><br />");

            // Add the header information
            Output.WriteLine("<table width=\"720px\" cellspacing=\"0px\">");
            Output.WriteLine("  <tr align=\"center\" bgcolor=\"#0022a7\"><td colspan=\"2\"><span style=\"color: White\"><b>" + session_state + "</b></span></td></tr>");
            Output.WriteLine("  <tr align=\"left\" bgcolor=\"#7d90d5\">");
            Output.WriteLine("    <th align=\"left\"><span style=\"color: White\">" + key + "</span></th>");
            Output.WriteLine("    <th align=\"left\"><span style=\"color: White\">" + objectTitle + "</span></th>");
            Output.WriteLine("  </tr>");

            try
            {
                // Now, get the information from the Session
                if (sessionKeys.Count == 0)
                {
                    Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
                    Output.WriteLine("  <tr align=\"left\">");
                    Output.WriteLine("    <td><i>" + Localization_Gateway.Internal.None_Placeholder(language) + "</i></td>");
                    Output.WriteLine("    <td><i>" + Localization_Gateway.Internal.None_Placeholder(language) + "</td>");
                    Output.WriteLine("  </tr>");
                }
                else
                {
                    foreach (string thisKey in sessionKeys)
                    {
                        // Add this row
                        session.TryGetValue(thisKey, out byte[] sessionValue);
                        Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
                        Output.WriteLine("  <tr align=\"left\">");
                        Output.WriteLine("    <td>" + thisKey + "</td>");
                        Output.WriteLine("    <td>" + (sessionValue != null ? "byte[" + sessionValue.Length + "]" : "NULL") + "</td>");
                        Output.WriteLine("  </tr>");
                    }
                }
            }
            catch (Exception)
            {
                Output.WriteLine("<strong>" + Localization_Gateway.Internal.Session_State_Error(language) + "</strong>");
            }

            // Close out this table
            Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"2\"></td></tr>");
            Output.WriteLine("</table>");
            Output.WriteLine("<br /><br />");
            Output.WriteLine();
        }

        #endregion

        #region Method to add the master tree of ALL aggrgeations

        /// <summary> Adds information about all aggregationPermissions to the response stream </summary>
        /// <param name="Output"> Stream to which to write the HTML for this subwriter </param>
        /// <param name="Tracer"> Trace object keeps a list of each method executed and important milestones in rendering </param>
        protected internal void add_aggregations_tree_html(TextWriter Output, Custom_Tracer Tracer)
        {
            Tracer.Add_Trace("Internal_HtmlSubwriter.add_aggregations_tree_html", "Rendering HTML");

            Output.WriteLine("<script type=\"text/javascript\" src=\"" + Static_Resources_Gateway.Jstree_Js + "\"></script>");

            // Get the hierarchy
            Aggregation_Hierarchy hierarchy = SobekEngineClient.Aggregations.Get_Aggregation_Hierarchy(Tracer);

            if (hierarchy != null)
            {
                string language = RequestSpecificValues.Current_Mode.Language;

                // Add the text
                Output.WriteLine("<div class=\"sbkIhsw_HomeText\">");
                Output.WriteLine("<p>" + Localization_Gateway.Internal.Aggregations_Tree_Intro(language) + "</p>");
                Output.WriteLine("<br />");


                RequestSpecificValues.Current_Mode.Internal_Type = Internal_Type_Enum.Aggregations_List;
                string url = UrlWriterHelper.Redirect_URL(RequestSpecificValues.Current_Mode);
                RequestSpecificValues.Current_Mode.Internal_Type = Internal_Type_Enum.Aggregations_Tree;

                Output.WriteLine("<p><a href=\"" + url + "\">" + Localization_Gateway.Internal.View_Table_View_Link(language) + "</a></p>");
                Output.WriteLine("<br />");

                Output.WriteLine("<blockquote>");
                Output.WriteLine("  <div style=\"text-align:right;\">");
                Output.WriteLine("    <a onclick=\"$('#aggregationTree').jstree('close_all');return false;\">" + Localization_Gateway.Internal.Collapse_All(language) + "</a> | ");
                Output.WriteLine("    <a onclick=\"$('#aggregationTree').jstree('open_all');return false;\">" + Localization_Gateway.Internal.Expand_All(language) + "</a>");
                Output.WriteLine("  </div>");


                Output.WriteLine("  <div id=\"aggregationTree\">");
                Output.WriteLine("    <ul>");
                Output.WriteLine("      <li>" + Localization_Gateway.Internal.Collection_Hierarchy(language));

                RequestSpecificValues.Current_Mode.Mode = Display_Mode_Enum.Aggregation;

                // Step through each node under this
                if (hierarchy.Collections.Count > 0)
                {
                    Output.WriteLine("        <ul>");
                    foreach (Item_Aggregation_Related_Aggregations childAggr in hierarchy.Collections)
                    {
                        // Set the aggregation value, for the redirect URL
                        RequestSpecificValues.Current_Mode.Aggregation = childAggr.Code.ToLower();

                        Output.WriteLine("          <li><a href=\"" + UrlWriterHelper.Redirect_URL(RequestSpecificValues.Current_Mode) + "\"><abbr title=\"" + childAggr.Description + "\">" + childAggr.Name + "</abbr></a>");

                        // Check the children nodes recursively
                        add_children_to_tree("            ", Output, childAggr);

                        Output.WriteLine("          </li>");
                    }
                    Output.WriteLine("        </ul>");
                }
                Output.WriteLine("      </li>");

                if (hierarchy.Institutions.Count > 0)
                {
                    Output.WriteLine("      <li>" + Localization_Gateway.Internal.Institutions(language));
                    Output.WriteLine("        <ul>");
                    foreach (Item_Aggregation_Related_Aggregations childAggr in hierarchy.Institutions)
                    {
                        if ((!childAggr.Hidden) && (childAggr.Active))
                        {
                            // Set the aggregation value, for the redirect URL
                            RequestSpecificValues.Current_Mode.Aggregation = childAggr.Code.ToLower();

                            Output.WriteLine("          <li><a href=\"" + UrlWriterHelper.Redirect_URL(RequestSpecificValues.Current_Mode) + "\"><abbr title=\"" + childAggr.Description + "\">" + childAggr.Name + "</abbr></a>");

                            // Check the children nodes recursively
                            add_children_to_tree("            ", Output, childAggr);

                            Output.WriteLine("          </li>");
                        }
                    }
                    Output.WriteLine("        </ul>");
                    Output.WriteLine("      </li>");
                }

                Output.WriteLine("    </ul>");
                Output.WriteLine("  </div>");
                Output.WriteLine("</blockquote>");
                Output.WriteLine("</div>");
                Output.WriteLine();

                Output.WriteLine("<script type=\"text/javascript\">");
                Output.WriteLine("   $('#aggregationTree').jstree().bind(\"select_node.jstree\", function (e, data) { var href = data.node.a_attr.href; document.location.href = href; });");
                Output.WriteLine("</script>");
                Output.WriteLine();

                // Restore the mode
                RequestSpecificValues.Current_Mode.Mode = Display_Mode_Enum.Internal;
                RequestSpecificValues.Current_Mode.Aggregation = String.Empty;
            }
        }


        private void add_children_to_tree(string LeadingSpaces, TextWriter Output, Item_Aggregation_Related_Aggregations Aggr)
        {
            // Step through each node under this
            if (Aggr.Children_Count > 0)
            {
                Output.WriteLine(LeadingSpaces + "<ul>");
                foreach (Item_Aggregation_Related_Aggregations childAggr in Aggr.Children)
                {
                    // Set the aggregation value, for the redirect URL
                    RequestSpecificValues.Current_Mode.Aggregation = childAggr.Code.ToLower();

                    if (childAggr.Children_Count > 0)
                    {
                        Output.WriteLine(LeadingSpaces + "  <li><a href=\"" + UrlWriterHelper.Redirect_URL(RequestSpecificValues.Current_Mode) + "\"><abbr title=\"" + childAggr.Description + "\">" + childAggr.Name + "</abbr></a>");

                        // Check the children nodes recursively
                        add_children_to_tree(LeadingSpaces + "   ", Output, childAggr);

                        Output.WriteLine(LeadingSpaces + "  </li>");
                    }
                    else
                    {
                        Output.WriteLine(LeadingSpaces + "  <li><a href=\"" + UrlWriterHelper.Redirect_URL(RequestSpecificValues.Current_Mode) + "\"><abbr title=\"" + childAggr.Description + "\">" + childAggr.Name + "</abbr></a></li>");
                    }

                }
                Output.WriteLine(LeadingSpaces + "</ul>");
            }
        }

        #endregion

        #region Method to add the master list of ALL aggregations

        /// <summary> Adds information about all aggregationPermissions to the response stream </summary>
        /// <param name="Output"> Stream to which to write the HTML for this subwriter </param>
        /// <param name="Tracer"> Trace object keeps a list of each method executed and important milestones in rendering </param>
        protected internal void add_aggregations_master_list_html(TextWriter Output, Custom_Tracer Tracer)
        {
            Tracer.Add_Trace("Internal_HtmlSubwriter.add_aggregations_master_list_html", "Rendering HTML");

            string language = RequestSpecificValues.Current_Mode.Language;

            // Add text at the top and sort the dataset if necessary
            Output.WriteLine("<div class=\"sbkIhsw_HomeText\">");
            Output.WriteLine("<p>" + Localization_Gateway.Internal.Aggregations_List_Intro(language) + "</p>");
            Output.WriteLine("<br />");
            RequestSpecificValues.Current_Mode.Internal_Type = Internal_Type_Enum.Aggregations_Tree;
            string url = UrlWriterHelper.Redirect_URL(RequestSpecificValues.Current_Mode);
            RequestSpecificValues.Current_Mode.Internal_Type = Internal_Type_Enum.Aggregations_List;

            Output.WriteLine("<p><a href=\"" + url + "\">" + Localization_Gateway.Internal.View_Tree_View_Link(language) + "</a></p>");
            Output.WriteLine("<br />");

            Output.WriteLine("  <table class=\"sbkIhsw_Table display\" id=\"adminMgmtTable\">");
            Output.WriteLine("    <thead>");
            Output.WriteLine("      <tr>");
            Output.WriteLine("        <th>" + Localization_Gateway.Internal.Code_Header(language) + "</th>");
            Output.WriteLine("        <th>" + Localization_Gateway.Internal.Type_Header(language) + "</th>");
            Output.WriteLine("        <th>" + Localization_Gateway.Internal.Name_Header(language) + "</th>");
            Output.WriteLine("        <th>" + Localization_Gateway.Internal.Active_Header(language) + "</th>");
            Output.WriteLine("        <th>" + Localization_Gateway.Internal.On_Home_Header(language) + "</th>");
            Output.WriteLine("        <th>" + Localization_Gateway.Internal.Parent_Header(language) + "</th>");
            Output.WriteLine("      </tr>");
            Output.WriteLine("    </thead>");

            Output.WriteLine("    <tfoot>");
            Output.WriteLine("      <tr>");
            Output.WriteLine("        <th><input id=\"intAggrCodeSearch\" type=\"text\" placeholder=\"" + Localization_Gateway.Internal.Search_Code_Placeholder(language) + "\" /></th>");
            Output.WriteLine("        <th>" + Localization_Gateway.Internal.Type_Header(language) + "</th>");
            Output.WriteLine("        <th><input id=\"intAggrNameSearch\"  type=\"text\" placeholder=\"" + Localization_Gateway.Internal.Search_Name_Placeholder(language) + "\" /></th>");
            Output.WriteLine("        <th>" + Localization_Gateway.Internal.Active_Header(language) + "</th>");
            Output.WriteLine("        <th>" + Localization_Gateway.Internal.On_Home_Header(language) + "</th>");
            Output.WriteLine("        <th>" + Localization_Gateway.Internal.Parent_Header(language) + "</th>");
            Output.WriteLine("      </tr>");
            Output.WriteLine("    </tfoot>");

            Output.WriteLine("    <tbody>");

            // Show all the aggregations
            RequestSpecificValues.Current_Mode.Mode = Display_Mode_Enum.Aggregation;
            string last_code = String.Empty;
            foreach (Item_Aggregation_Related_Aggregations thisAggr in UI_ApplicationCache_Gateway.Aggregations.All_Aggregations)
            {
                if (thisAggr.Code != last_code)
                {
                    last_code = thisAggr.Code;

                    // Build the action links
                    if (thisAggr.Active)
                        Output.WriteLine("      <tr>");
                    //                      Output.WriteLine("        <td class=\"sbkAsav_ActionLink\" >( <a title=\"Click to view this item aggregation\" href=\"" + RequestSpecificValues.Current_Mode.Base_URL + "l/" + thisAggr.Code + "\">view</a> )");
                    else
                        Output.WriteLine("      <tr>");

                    // Special code to start istitutions with a small letter 'i'
                    string code = thisAggr.Code;
                    if ((thisAggr.Type.IndexOf("Institution", StringComparison.InvariantCultureIgnoreCase) >= 0) && (code[0] == 'I') && (code.Length > 1))
                    {
                        code = "i" + code.Substring(1);
                    }

                    // Get the URL
                    string link_url = RequestSpecificValues.Current_Mode.Base_URL + "/" + code.ToLower();

                    // Add the rest of the row with data
                    Output.WriteLine("        <td><a href=\"" + link_url + "\">" + code + "</a></td>");
                    Output.WriteLine("        <td>" + thisAggr.Type + "</td>");
                    Output.WriteLine("        <td><a href=\"" + link_url + "\">" + thisAggr.Name + "</a></td>");

                    Output.WriteLine(thisAggr.Active ? "        <td>Y</td>" : "        <td>N</td>");

                    Output.WriteLine(thisAggr.Thematic_Heading != null ? "        <td>Y</td>" : "        <td>N</td>");
                    if (thisAggr.Parent_Count > 0)
                    {
                        Output.WriteLine("        <td>" + thisAggr.Parents[0].Code + "</td>");
                    }
                    else
                    {
                        Output.WriteLine("        <td></td>");
                    }
                    Output.WriteLine("      </tr>");
                }
            }

            Output.WriteLine("    </tbody>");
            Output.WriteLine("  </table>");

            Output.WriteLine("<script type=\"text/javascript\">");
            Output.WriteLine("    $(document).ready(function() { ");
            Output.WriteLine("        var table = $('#adminMgmtTable').DataTable({ ");

            // If 100 or less aggregations, suppress paging
            if (UI_ApplicationCache_Gateway.Aggregations.All_Aggregations.Count <= 100)
            {
                Output.WriteLine("            \"paging\":   false, ");
                Output.WriteLine("            \"info\":   false, ");
            }
            else
            {
                Output.WriteLine("            \"lengthMenu\": [ [50, 100, -1], [50, 100, \"All\"] ], ");
                Output.WriteLine("            \"pageLength\":  50, ");
            }

            Output.WriteLine("            initComplete: function () {");
            Output.WriteLine("                var api = this.api();");

            Output.WriteLine("                api.columns().indexes().flatten().each( function ( i ) {");
            Output.WriteLine("                    if (( i == 1 || i == 3 || i == 4 || i == 5 )) {");
            Output.WriteLine("                        var column = api.column( i );");
            Output.WriteLine("                        var select = $('<select><option value=\"\"></option></select>')");
            Output.WriteLine("                                 .appendTo( $(column.footer()).empty() )");
            Output.WriteLine("                                 .on( 'change', function () {");
            Output.WriteLine("                                       var val = $.fn.dataTable.util.escapeRegex($(this).val());");
            Output.WriteLine("                                       column.search( val ? '^'+val+'$' : '', true, false ).draw();");
            Output.WriteLine("                                        } );");
            Output.WriteLine("                                 column.data().unique().sort().each( function ( d, j ) {");
            Output.WriteLine("                                      select.append( '<option value=\"'+d+'\">'+d+'</option>' )");
            Output.WriteLine("                                 } );");
            Output.WriteLine("                        }");
            Output.WriteLine("                    } );");
            Output.WriteLine("               }");
            Output.WriteLine("         });");

            Output.WriteLine("         $('#intAggrCodeSearch').on( 'keyup change', function () { table.column( 0 ).search( this.value ).draw(); } );");
            Output.WriteLine("         $('#intAggrNameSearch').on( 'keyup change', function () { table.column( 2 ).search( this.value ).draw(); } );");

            Output.WriteLine("         $('#adminMgmtTable').on('click', 'tr', function(ev) {");
            Output.WriteLine("             var aData = $('#adminMgmtTable').dataTable().fnGetData(this);");
            Output.WriteLine("             key = aData[0];");
            Output.WriteLine("             window.location.href = \"" + RequestSpecificValues.Current_Mode.Base_URL + "/\" + key;");
            Output.WriteLine("             ev.preventDefault();");
            Output.WriteLine("             ev.stopPropagation();");
            Output.WriteLine("          });");
            Output.WriteLine("    } );");

            Output.WriteLine("</script>");
            Output.WriteLine();


            Output.WriteLine("  <br />");
            Output.WriteLine("</div>");
            Output.WriteLine();
        }

        #endregion

        #region Method to add the list of all new and recently changed items

        /// <summary> Adds the list of all new and recently changed items to the response stream </summary>
        /// <param name="Output"> Stream to which to write the HTML for this subwriter </param>
        /// <param name="New_Items"> The list of recently added/changed items to display </param>
        /// <param name="Tracer"> Trace object keeps a list of each method executed and important milestones in rendering </param>
        protected internal void add_new_item_html(TextWriter Output, DataTable New_Items, Custom_Tracer Tracer)
        {
            string language = RequestSpecificValues.Current_Mode.Language;

            // Create the strings for the sub views
            string BIBID = Localization_Gateway.Internal.Bibid_Vid_Header(language);
            string last_event = Localization_Gateway.Internal.Date_Header(language);
            string mets_type = Localization_Gateway.Internal.Mets_Type_Header(language);
            string ALL_TYPES = Localization_Gateway.Internal.All_Types(language);

            string online_edits = Localization_Gateway.Internal.Online_Edits(language);
            string online_submits = Localization_Gateway.Internal.Online_Submits(language);
            string visibility = Localization_Gateway.Internal.Visibility_Changes(language);
            string bulk_loaded = Localization_Gateway.Internal.Bulk_Loaded(language);
            string post_processed = Localization_Gateway.Internal.Post_Processed(language);

            // If there was no count, or no rows returned, say something
            if ((New_Items == null) || (New_Items.Rows.Count == 0))
            {
                Output.WriteLine("<br /><br /><strong>" + Localization_Gateway.Internal.No_New_Items_Message(language) + "</strong><br /><br />");
                return;
            }

            // Get the submode
            string type = RequestSpecificValues.Current_Mode.Info_Browse_Mode;

            // Make sure the value is one of the set values
            if ((type != String.Empty) && (type != "all") && (type != "edit") && (type != "submit") && (type != "visibility") && (type != "bulkloaded") && (type != "postprocessed"))
                type = String.Empty;

            // set to ALL as default if there aren't an extraordinary number of rows
            if ((New_Items.Rows.Count < 5000) && (type.Length == 0))
            {
                type = "all";
            }

            // Add the number of each metadata type to the end
            online_edits = online_edits + " ( " + New_Items.Select("WorkFlowName = 'Online Edit'").Length + " )";
            online_submits = online_submits + " ( " + New_Items.Select("WorkFlowName = 'Online Submit'").Length + " )";
            visibility = visibility + " ( " + New_Items.Select("WorkFlowName='Made Private' or WorkFlowName='Made Public' or WorkFlowName='Made Restricted'").Length + " )";
            bulk_loaded = bulk_loaded + " ( " + New_Items.Select("WorkFlowName = 'Bulk Loaded'").Length + " )";
            post_processed = post_processed + " ( " + New_Items.Select("WorkFlowName = 'Post-Processed'").Length + " )";


            Output.WriteLine("<div id=\"sbkInternalHsw_ViewSelectDiv\">");
            Output.WriteLine("  <ul class=\"sbk_FauxDownwardTabsList\">");

            string baseLocationUrl = String.IsNullOrEmpty(UI_ApplicationCache_Gateway.Settings.Servers.Base_SobekCM_Location_Relative) ? String.Empty : UI_ApplicationCache_Gateway.Settings.Servers.Base_SobekCM_Location_Relative;


            if (type == "all")
            {
                Output.WriteLine("    <li class=\"current\">" + ALL_TYPES + "</li>");
            }
            else
            {
                RequestSpecificValues.Current_Mode.Info_Browse_Mode = "all";
                Output.WriteLine("    <li><a href=\"" + baseLocationUrl + UrlWriterHelper.Redirect_URL(RequestSpecificValues.Current_Mode) + "\">" + ALL_TYPES + "</a></li>");
            }

            if (type == "edit")
            {
                Output.WriteLine("    <li class=\"current\">" + online_edits + "</li>");
            }
            else
            {
                RequestSpecificValues.Current_Mode.Info_Browse_Mode = "edit";
                Output.WriteLine("    <li><a href=\"" + baseLocationUrl + UrlWriterHelper.Redirect_URL(RequestSpecificValues.Current_Mode) + "\">" + online_edits + "</a></li>");
            }

            if (type == "submit")
            {
                Output.WriteLine("    <li class=\"current\">" + online_submits + "</li>");
            }
            else
            {
                RequestSpecificValues.Current_Mode.Info_Browse_Mode = "submit";
                Output.WriteLine("    <li><a href=\"" + baseLocationUrl + UrlWriterHelper.Redirect_URL(RequestSpecificValues.Current_Mode) + "\">" + online_submits + "</a></li>");
            }

            if (type == "visibility")
            {
                Output.WriteLine("    <li class=\"current\">" + visibility + "</li>");
            }
            else
            {
                RequestSpecificValues.Current_Mode.Info_Browse_Mode = "visibility";
                Output.WriteLine("    <li><a href=\"" + baseLocationUrl + UrlWriterHelper.Redirect_URL(RequestSpecificValues.Current_Mode) + "\">" + visibility + "</a></li>");
            }

            if (type == "bulkloaded")
            {
                Output.WriteLine("    <li class=\"current\">" + bulk_loaded + "</li>");
            }
            else
            {
                RequestSpecificValues.Current_Mode.Info_Browse_Mode = "bulkloaded";
                Output.WriteLine("    <li><a href=\"" + baseLocationUrl + UrlWriterHelper.Redirect_URL(RequestSpecificValues.Current_Mode) + "\">" + bulk_loaded + "</a></li>");
            }

            if (type == "postprocessed")
            {
                Output.WriteLine("    <li class=\"current\">" + post_processed + "</li>");
            }
            else
            {
                RequestSpecificValues.Current_Mode.Info_Browse_Mode = "postprocessed";
                Output.WriteLine("    <li><a href=\"" + baseLocationUrl + UrlWriterHelper.Redirect_URL(RequestSpecificValues.Current_Mode) + "\">" + post_processed + "</a></li>");
            }
            Output.WriteLine("</ul>");
            Output.WriteLine("</div>");
            RequestSpecificValues.Current_Mode.Info_Browse_Mode = type;

            Output.WriteLine("<br />");
            Output.WriteLine("");

            string thisDate;
            string lastDate = String.Empty;

            bool display_user = false;
            int columns = 3;
            int width = 600;
            if ((RequestSpecificValues.Current_User != null) && (RequestSpecificValues.Current_User.Is_Internal_User))
            {
                display_user = true;
                columns = 4;
                width = 750;
            }

            if (type.Length == 0)
            {
                Output.WriteLine("<div class=\"SobekText\">");
                Output.WriteLine("<br />");
                Output.WriteLine("<p>" + Localization_Gateway.Internal.Large_Update_Count_Message(language) + "</p>");
                Output.WriteLine("<p>" + Localization_Gateway.Internal.Select_Update_Type_Message(language) + "</p>");
                Output.WriteLine("<br />");
                Output.WriteLine("<br />");
                Output.WriteLine("</div>");
                return;
            }

            Output.WriteLine("<br />");


            // Now, add each line
            if (type == "all")
            {
                if (New_Items.Rows.Count > 0)
                {
                    // Add the header information
                    Output.WriteLine("<table width=\"" + width + "px\" border=\"0px\" cellspacing=\"0px\">");
                    Output.WriteLine("  <tr align=\"left\" bgcolor=\"#0022a7\" >");
                    Output.WriteLine("    <th align=\"left\"><span style=\"color: White\"><b>" + BIBID + "</b></span></th>");
                    Output.WriteLine("    <th align=\"left\"><span style=\"color: White\"><b>" + last_event + "</b></span></th>");
                    Output.WriteLine("    <th align=\"left\"><span style=\"color: White\"><b>" + mets_type + "</b></span></th>");
                    if (display_user)
                    {
                        Output.WriteLine("    <th align=\"left\"><span style=\"color: White\"><b>" + Localization_Gateway.Internal.User_Header(language) + "</b></span></th>");
                    }
                    Output.WriteLine("  </tr>");

                    foreach (DataRow thisRow in New_Items.Rows)
                    {
                        // Get this date
                        thisDate = thisRow[2].ToString().Split(" ".ToCharArray())[0];

                        // Is this a new date?
                        if (thisDate != lastDate)
                        {
                            Output.WriteLine("  <tr align=\"left\" bgcolor=\"#7d90d5\" ><td colspan=\"" + columns + "\"><span style=\"color: White\"><b>" + thisDate + "</b></span></td></tr>");

                            lastDate = thisDate;
                        }

                        Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"" + columns + "\"></td></tr>");
                        Output.WriteLine("  <tr align=\"left\">");
                        Output.WriteLine("    <td><a href=\"" + RequestSpecificValues.Current_Mode.Base_URL + thisRow[0] + "/" + thisRow[1] + "\">" + thisRow[0] + " : " + thisRow[1] + "</a></td>");
                        Output.WriteLine("    <td>" + thisRow[2] + "</td>");
                        Output.WriteLine("    <td>" + thisRow[3] + "</td>");

                        if (display_user)
                        {
                            Output.WriteLine("    <td>" + thisRow[4] + "</td>");
                        }

                        Output.WriteLine("  </tr>");
                    }

                    Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"" + columns + "\"></td></tr>");
                    Output.WriteLine("</table>");
                }
                else
                {
                    Output.WriteLine("<br />");
                    Output.WriteLine("<center>" + Localization_Gateway.Internal.No_Tracking_Info_Message(language) + "</center>");
                    Output.WriteLine("<br />");
                }
            }
            else
            {
                DataRow[] matches = null;
                switch (type)
                {
                    case "edit":
                        matches = New_Items.Select("WorkFlowName = 'Online Edit'");
                        break;

                    case "submit":
                        matches = New_Items.Select("WorkFlowName = 'Online Submit'");
                        break;

                    case "visibility":
                        matches = New_Items.Select("WorkFlowName='Made Private' or WorkFlowName='Made Public' or WorkFlowName='Made Restricted'");
                        break;

                    case "bulkloaded":
                        matches = New_Items.Select("WorkFlowName = 'Bulk Loaded'");
                        break;

                    case "postprocessed":
                        matches = New_Items.Select("WorkFlowName = 'Post-Processed'");
                        break;
                }

                if ((matches != null) && (matches.Length > 0))
                {
                    // Add the header information
                    Output.WriteLine("<table width=\"" + width + "px\" border=\"0px\" cellspacing=\"0px\">");
                    Output.WriteLine("  <tr align=\"left\" bgcolor=\"#0022a7\" >");
                    Output.WriteLine("    <th><span style=\"color: White\"><b>" + BIBID + "</b></span></th>");
                    Output.WriteLine("    <th><span style=\"color: White\"><b>" + last_event + "</b></span></th>");
                    Output.WriteLine("    <th><span style=\"color: White\"><b>" + mets_type + "</b></span></th>");
                    if (display_user)
                    {
                        Output.WriteLine("    <th><span style=\"color: White\"><b>" + Localization_Gateway.Internal.User_Header(language) + "</b></span></th>");
                    }
                    Output.WriteLine("  </tr>");

                    foreach (DataRow thisRow in matches)
                    {
                        // Get this date
                        thisDate = thisRow[2].ToString().Split(" ".ToCharArray())[0];

                        // Is this a new date?
                        if (thisDate != lastDate)
                        {
                            Output.WriteLine("  <tr align=\"left\" bgcolor=\"#7d90d5\" ><td colspan=\"" + columns + "\"><span style=\"color: White\"><b>" + thisDate + "</b></span></td></tr>");

                            lastDate = thisDate;
                        }

                        Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"" + columns + "\"></td></tr>");
                        Output.WriteLine("  <tr align=\"left\">");
                        Output.WriteLine("    <td><a href=\"" + RequestSpecificValues.Current_Mode.Base_URL + thisRow[0] + "/" + thisRow[1] + "\">" + thisRow[0] + " : " + thisRow[1] + "</a></td>");
                        Output.WriteLine("    <td>" + thisRow[2] + "</td>");
                        Output.WriteLine("    <td>" + thisRow[3] + "</td>");

                        if (display_user)
                        {
                            Output.WriteLine("    <td>" + thisRow[4] + "</td>");
                        }

                        Output.WriteLine("  </tr>");
                    }

                    Output.WriteLine("  <tr><td bgcolor=\"#e7e7e7\" colspan=\"" + columns + "\"></td></tr>");
                    Output.WriteLine("</table>");
                }
                else
                {
                    Output.WriteLine("<br />");
                    Output.WriteLine("<center>" + Localization_Gateway.Internal.No_Info_Message(language) + "</center>");
                    Output.WriteLine("<br />");
                }
            }

            Output.WriteLine("<br />");
            Output.WriteLine();
        }

        #endregion


        /// <summary> Write any additional values within the HTML Head of the
        /// final served page </summary>
        /// <param name="Output"> Output stream currently within the HTML head tags </param>
        /// <param name="Tracer"> Trace object keeps a list of each method executed and important milestones in rendering </param>
        public override void Write_Within_HTML_Head(TextWriter Output, Custom_Tracer Tracer)
        {
            Output.WriteLine("  <meta name=\"robots\" content=\"noindex, nofollow\" />");

            Output.WriteLine("  <link href=\"" + Static_Resources_Gateway.Sobekcm_Mysobek_Css + "\" rel=\"stylesheet\" type=\"text/css\" />");

            if (RequestSpecificValues.Current_Mode.Internal_Type == Internal_Type_Enum.Aggregations_List)
            {
                Output.WriteLine("  <link href=\"" + Static_Resources_Gateway.Sobekcm_Datatables_Css + "\" rel=\"stylesheet\" type=\"text/css\" />");
                Output.WriteLine("  <script type=\"text/javascript\" src=\"" + Static_Resources_Gateway.Jquery_Datatables_Js + "\" ></script>");
            }

            if (RequestSpecificValues.Current_Mode.Internal_Type == Internal_Type_Enum.Aggregations_Tree)
            {
                Output.WriteLine("  <link rel=\"stylesheet\" href=\"" + Static_Resources_Gateway.Jstree_Css + "\" />");
            }

        }

        /// <summary>  Gets the collection of special behaviors which this subwriter
        /// requests from the main HTML writer.  </summary>
        public override List<HtmlSubwriter_Behaviors_Enum> Subwriter_Behaviors
        {
            get { return new List<HtmlSubwriter_Behaviors_Enum> { HtmlSubwriter_Behaviors_Enum.Suppress_Banner }; }
        }

        /// <summary> Gets the CSS class of the container that the page is wrapped within </summary>
        public override string Container_CssClass
        {
            get
            {
                if (RequestSpecificValues.Current_Mode.Internal_Type == Internal_Type_Enum.Wordmarks)
                    return "container-inner1000";

                if (RequestSpecificValues.Current_Mode.Internal_Type == Internal_Type_Enum.Aggregations_List)
                    return "container-inner1215";

                return base.Container_CssClass;
            }
        }
    }
}
